# vibecomfy: generated
# For hand-editing, run: python -m vibecomfy.cli copy-to-recipe <id>
# vibecomfy: surface=canonical
"""Auto-generated ready_template — use python -m vibecomfy.cli copy-to-recipe <id> for hand-editing."""
from __future__ import annotations

from vibecomfy.templates import InputSpec, ReadyMetadata, new_workflow, node as raw_call, ref
from vibecomfy.workflow import VibeWorkflow
from vibecomfy.nodes.core import BasicGuider, BasicScheduler, CLIPLoader, ComfyMathExpression, KSamplerSelect, RandomNoise, ResolutionSelector, SaveVideo, UNETLoader, VAELoader


AUDIO_VAE_NAME = 'minimax_h3_audio_vae_fp32.safetensors'
CLIP_NAME = 'qwen3vl_32b_minimax_h3_int8_convrot.safetensors'
DEFAULT_PROMPT = 'PRIESTESS OF THE BLUE HOUR — Dance Music Video\n\nHigh-end 2D anime cinematic look, dance music-video style — delicate, refined hand-drawn animation: fine precise linework with elegant variation in line weight, soft watercolor and airbrush shading instead of hard cel shadows, subtle gradient tints across skin and fabric, gentle film grain, volumetric haze, anamorphic framing, shallow depth of field. The palette is restrained and premium: deep blue-hour dusk, muted neon accents, and the dancer\'s warm white-and-gold as the only saturated warmth. Evoking the delicate hand-drawn elegance of Makoto Shinkai\'s character work and KyoAni\'s refined, graceful linework — never crude, never exaggerated. This is the centerpiece dance sequence of an anime music video: each motion is emotional, fluid, alive.\n\nScene overview: at blue-hour dusk on an empty rain-wet plaza between glowing towers, the dancer moves alone, choreography building from stillness to explosive, every move landing on the musical beats. Her long blonde hair catches the wind; her white-and-gold priestess vestments — layered robes with gold trim, church embroidery, a small pendant at her neck — flare and settle with each motion. Beside her, a cute toy bear — soft plush, glass-button eyes, stitched paws — floats gently, emitting a faint golden glow and a trail of tiny twinkling stars and light particles that drift and spin in the air, catching the neon light like miniature fireflies, reweaving into a halo orbit as she moves. No transformation, no destruction — just her, her dance, the bear, and the city\'s glow.\n\nCharacter design: slender, graceful proportions; a refined, gentle face with soft features and a serene, slightly devout expression — eyes half-lidded, calm; long blonde hair rendered strand by strand, flowing and luminous; her signature white-and-gold priestess outfit drawn with fine elegant lines, layers of cloth that lift and settle beautifully in motion.\n\n0s–1.5s Shot 1 — The Stillness — wide shot: the dancer stands motionless at the center of the plaza, eyes closed, wind catching her hair and the hem of her robes, city lights and mist behind her. The toy bear floats at her side, its button eyes glowing softly, a warm radiance pulsing from its little chest, and a ring of golden sparkles circles it slowly. Behind her, the towers shimmer with neon; the wet pavement mirrors the sky. She breathes — the bear\'s glow flickers gently.\n\n1s–2.5s Shot 2 — The Unfolding — she begins to move: a slow arm extension turning into a spin, long hair sweeping through the air. Her robes flare with the rotation, white cloth catching the blue light, gold trim tracing glowing arcs; the floating sparkles and starlight spiral with her like a comet of tiny lights, one cluster passing close to the camera, its warm glints reflecting in the bear\'s glassy eyes. She opens her eyes — serene, focused — as she completes the turn. Neon light trails and passing cars streak softly behind her, a slight slow-motion feel.\n\n2.5s–4s Shot 3 — The Leap — fast footwork into a leaping turn, body stretching mid-air, robes and hair streaming upward like wings, the halo of golden particles exploding outward and reforming as she twists, the toy bear tumbling playfully through the air alongside her. Wet pavement reflections flash below, softly blurred; the city\'s glow blooms around her silhouette as she soars through the frame. The motion is fluid, weightless, precise — every beat landing.\n\n4s–5s Shot 4 — The Landing — freeze: she lands softly, the momentum settling through her body, robes settling around her, the sparkling lights returning to the bear, which floats down and nestles gently at her side. She strikes the final pose — one arm extended, palm open, head tilted, eyes lowered, a quiet smile. Her lips part and she whispers, "I am the hour." — silhouette against the glowing city, the last tiny star drifting down past her face, holding. Only the shimmer of heat and city light in the air, and the bear\'s soft glow fading.\n\nCamera: each shot its own angle, cuts clean and hard, no dissolves — precise cuts on the beat with a slight, elegant frame jitter on each accent hit; soft lens bloom where the sparkles catch the light; the golden glow of the bear as a secondary light source alongside the blue-hour dusk, warm highlights tracing her profile and the edges of her robes.\n\nAudio: a restrained, atmospheric score — wind, distant city ambience, footsteps on wet pavement, a soft tinkling chime accompanying the bear\'s sparkles on each accent beat, low strings and piano underneath, an accent hit on each beat, the score bursting at 4s as she lands, closing the final 1s in near-silence with only the wind, her breathing, her soft whisper fading, and the faint rustle of plush fur settling.\n\nNo text, subtitles, logos or watermarks of any kind, no 3D-CG or cel-shaded video-game look, no photorealism, no rough or crude linework — keep the delicate hand-drawn 2D anime texture with fine, elegant lines throughout.'
UNET_NAME = 'minimax_h3_fl2va_pruned_fp8_scaled.safetensors'
VIDEO_VAE_NAME = 'minimax_h3_video_vae_fp16.safetensors'
DEFAULT_SEED = 123


PUBLIC_INPUT_METADATA = {
    'model': InputSpec(node=ref('unetloader'), field='unet_name', default=None, infer_type=False),
    'steps': InputSpec(node=ref('basicscheduler'), field='steps', default=None, infer_type=False),
    'seed': InputSpec(node=ref('randomnoise'), field='noise_seed', default=DEFAULT_SEED, type='INT'),
}

CANONICAL_CUSTODY = {'resolutionselector': {'id': '115',
                        'uid': '115',
                        'class_type': 'ResolutionSelector',
                        'native_ports': {'native_input_names': [],
                                         'native_output_names': ['width', 'height'],
                                         'native_input_types': [],
                                         'native_output_types': ['INT', 'INT'],
                                         'native_input_optional': [],
                                         'native_input_asset_kinds': None,
                                         'native_output_slots': None},
                        'metadata': {'schema_source': {'provider': 'object_info_index',
                                                       'path': None,
                                                       'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                       'server_url': None,
                                                       'package': 'comfy_core',
                                                       'version': None,
                                                       'hash': None,
                                                       'confidence': 0.7},
                                     'provenance': 'untrusted_source',
                                     'output_names': ['width', 'height'],
                                     'output_types': ['INT', 'INT'],
                                     'keep_defaults': ['aspect_ratio', 'megapixels', 'multiple']},
                        'widget_channels': {},
                        'none_input_fields': [],
                        'none_widget_fields': [],
                        'output_slot_names': {}},
 'markdownnote': {'id': '116',
                  'uid': '116',
                  'class_type': 'MarkdownNote',
                  'native_ports': {'native_input_names': [],
                                   'native_output_names': [],
                                   'native_input_types': [],
                                   'native_output_types': [],
                                   'native_input_optional': [],
                                   'native_input_asset_kinds': None,
                                   'native_output_slots': None},
                  'metadata': {'schema_source': {'provider': 'widget_schema',
                                                 'path': None,
                                                 'cache_path': None,
                                                 'server_url': None,
                                                 'package': None,
                                                 'version': None,
                                                 'hash': None,
                                                 'confidence': 0.3},
                               'provenance': 'untrusted_source',
                               'keep_defaults': ['unused_widget_0']},
                  'widget_channels': {},
                  'none_input_fields': [],
                  'none_widget_fields': [],
                  'output_slot_names': {}},
 'markdownnote_2': {'id': '117',
                    'uid': '117',
                    'class_type': 'MarkdownNote',
                    'native_ports': {'native_input_names': [],
                                     'native_output_names': [],
                                     'native_input_types': [],
                                     'native_output_types': [],
                                     'native_input_optional': [],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'widget_schema',
                                                   'path': None,
                                                   'cache_path': None,
                                                   'server_url': None,
                                                   'package': None,
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.3},
                                 'provenance': 'untrusted_source',
                                 'keep_defaults': ['unused_widget_0']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'markdownnote_3': {'id': '118',
                    'uid': '118',
                    'class_type': 'MarkdownNote',
                    'native_ports': {'native_input_names': [],
                                     'native_output_names': [],
                                     'native_input_types': [],
                                     'native_output_types': [],
                                     'native_input_optional': [],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'widget_schema',
                                                   'path': None,
                                                   'cache_path': None,
                                                   'server_url': None,
                                                   'package': None,
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.3},
                                 'provenance': 'untrusted_source',
                                 'keep_defaults': ['unused_widget_0']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'lanpaint_videomaskeditor': {'id': '164',
                              'uid': '164',
                              'class_type': 'LanPaint_VideoMaskEditor',
                              'native_ports': {'native_input_names': [],
                                               'native_output_names': ['video', 'mask', 'audio_mask'],
                                               'native_input_types': [],
                                               'native_output_types': ['VIDEO', 'MASK', 'MASK'],
                                               'native_input_optional': [],
                                               'native_input_asset_kinds': None,
                                               'native_output_slots': None},
                              'metadata': {'schema_source': {'provider': 'widget_schema',
                                                             'path': None,
                                                             'cache_path': None,
                                                             'server_url': None,
                                                             'package': None,
                                                             'version': None,
                                                             'hash': None,
                                                             'confidence': 0.3},
                                           'provenance': 'untrusted_source',
                                           'keep_defaults': ['audio_mask',
                                                             'keyframes',
                                                             'unused_widget_3',
                                                             'unused_widget_4',
                                                             'video']},
                              'widget_channels': {},
                              'none_input_fields': [],
                              'none_widget_fields': [],
                              'output_slot_names': {}},
 'markdownnote_4': {'id': '170',
                    'uid': '170',
                    'class_type': 'MarkdownNote',
                    'native_ports': {'native_input_names': [],
                                     'native_output_names': [],
                                     'native_input_types': [],
                                     'native_output_types': [],
                                     'native_input_optional': [],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'widget_schema',
                                                   'path': None,
                                                   'cache_path': None,
                                                   'server_url': None,
                                                   'package': None,
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.3},
                                 'provenance': 'untrusted_source',
                                 'keep_defaults': ['unused_widget_0']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'comfymathexpression': {'id': '105::107',
                         'uid': '105::107',
                         'class_type': 'ComfyMathExpression',
                         'native_ports': {'native_input_names': ['values.a', 'values.b'],
                                          'native_output_names': ['FLOAT', 'INT', 'BOOL'],
                                          'native_input_types': ['FLOAT,INT,BOOLEAN', 'FLOAT,INT,BOOLEAN'],
                                          'native_output_types': ['FLOAT', 'INT', 'BOOLEAN'],
                                          'native_input_optional': [False, True],
                                          'native_input_asset_kinds': None,
                                          'native_output_slots': None},
                         'metadata': {'schema_source': {'provider': 'object_info_index',
                                                        'path': None,
                                                        'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                        'server_url': None,
                                                        'package': 'comfy_core',
                                                        'version': None,
                                                        'hash': None,
                                                        'confidence': 0.7},
                                      'provenance': 'untrusted_source',
                                      'output_names': ['FLOAT', 'INT', 'BOOL'],
                                      'output_types': ['FLOAT', 'INT', 'BOOLEAN'],
                                      'keep_defaults': ['expression']},
                         'widget_channels': {},
                         'none_input_fields': [],
                         'none_widget_fields': [],
                         'output_slot_names': {}},
 'vaeloader': {'id': '105::11',
               'uid': '105::11',
               'class_type': 'VAELoader',
               'native_ports': {'native_input_names': ['vae_name'],
                                'native_output_names': ['VAE'],
                                'native_input_types': ['COMBO'],
                                'native_output_types': ['VAE'],
                                'native_input_optional': [False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'output_names': ['VAE'],
                            'output_types': ['VAE'],
                            'keep_defaults': ['vae_name']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}},
 'cliploader': {'id': '105::13',
                'uid': '105::13',
                'class_type': 'CLIPLoader',
                'native_ports': {'native_input_names': ['clip_name'],
                                 'native_output_names': ['CLIP'],
                                 'native_input_types': ['COMBO'],
                                 'native_output_types': ['CLIP'],
                                 'native_input_optional': [False],
                                 'native_input_asset_kinds': None,
                                 'native_output_slots': None},
                'metadata': {'schema_source': {'provider': 'object_info_index',
                                               'path': None,
                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                               'server_url': None,
                                               'package': 'comfy_core',
                                               'version': None,
                                               'hash': None,
                                               'confidence': 0.7},
                             'provenance': 'untrusted_source',
                             'output_names': ['CLIP'],
                             'output_types': ['CLIP'],
                             'keep_defaults': ['clip_name', 'device', 'type']},
                'widget_channels': {},
                'none_input_fields': [],
                'none_widget_fields': [],
                'output_slot_names': {}},
 'randomnoise': {'id': '105::15',
                 'uid': '105::15',
                 'class_type': 'RandomNoise',
                 'native_ports': {'native_input_names': ['noise_seed'],
                                  'native_output_names': ['NOISE'],
                                  'native_input_types': ['INT'],
                                  'native_output_types': ['NOISE'],
                                  'native_input_optional': [False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['NOISE'],
                              'output_types': ['NOISE'],
                              'keep_defaults': ['control_after_generate']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'ksamplerselect': {'id': '105::17',
                    'uid': '105::17',
                    'class_type': 'KSamplerSelect',
                    'native_ports': {'native_input_names': [],
                                     'native_output_names': ['SAMPLER'],
                                     'native_input_types': [],
                                     'native_output_types': ['SAMPLER'],
                                     'native_input_optional': [],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['SAMPLER'],
                                 'output_types': ['SAMPLER'],
                                 'keep_defaults': ['sampler_name']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'vaeloader_2': {'id': '105::24',
                 'uid': '105::24',
                 'class_type': 'VAELoader',
                 'native_ports': {'native_input_names': ['vae_name'],
                                  'native_output_names': ['VAE'],
                                  'native_input_types': ['COMBO'],
                                  'native_output_types': ['VAE'],
                                  'native_input_optional': [False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['VAE'],
                              'output_types': ['VAE'],
                              'keep_defaults': ['vae_name']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'unetloader': {'id': '105::6',
                'uid': '105::6',
                'class_type': 'UNETLoader',
                'native_ports': {'native_input_names': ['unet_name'],
                                 'native_output_names': ['MODEL'],
                                 'native_input_types': ['COMBO'],
                                 'native_output_types': ['MODEL'],
                                 'native_input_optional': [False],
                                 'native_input_asset_kinds': None,
                                 'native_output_slots': None},
                'metadata': {'schema_source': {'provider': 'object_info_index',
                                               'path': None,
                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                               'server_url': None,
                                               'package': 'comfy_core',
                                               'version': None,
                                               'hash': None,
                                               'confidence': 0.7},
                             'provenance': 'untrusted_source',
                             'output_names': ['MODEL'],
                             'output_types': ['MODEL'],
                             'keep_defaults': ['unet_name', 'weight_dtype']},
                'widget_channels': {},
                'none_input_fields': [],
                'none_widget_fields': [],
                'output_slot_names': {}},
 'minimaxh3imagetovideo': {'id': '105::104',
                           'uid': '105::104',
                           'class_type': 'MiniMaxH3ImageToVideo',
                           'native_ports': {'native_input_names': ['clip',
                                                                   'vae',
                                                                   'first_frame',
                                                                   'last_frame',
                                                                   'prompt',
                                                                   'width',
                                                                   'height',
                                                                   'length'],
                                            'native_output_names': ['positive', 'LATENT'],
                                            'native_input_types': ['CLIP',
                                                                   'VAE',
                                                                   'IMAGE',
                                                                   'IMAGE',
                                                                   'STRING',
                                                                   'INT',
                                                                   'INT',
                                                                   'INT'],
                                            'native_output_types': ['CONDITIONING', 'LATENT'],
                                            'native_input_optional': [False,
                                                                      False,
                                                                      True,
                                                                      True,
                                                                      False,
                                                                      False,
                                                                      False,
                                                                      False],
                                            'native_input_asset_kinds': None,
                                            'native_output_slots': None},
                           'metadata': {'schema_source': {'provider': 'widget_schema',
                                                          'path': None,
                                                          'cache_path': None,
                                                          'server_url': None,
                                                          'package': None,
                                                          'version': None,
                                                          'hash': None,
                                                          'confidence': 0.3},
                                        'provenance': 'untrusted_source',
                                        'keep_defaults': ['prompt']},
                           'widget_channels': {},
                           'none_input_fields': [],
                           'none_widget_fields': [],
                           'output_slot_names': {}},
 'lanpaint_avencode': {'id': '105::166',
                       'uid': '105::166',
                       'class_type': 'LanPaint_AVEncode',
                       'native_ports': {'native_input_names': ['video',
                                                               'vae',
                                                               'audio_vae',
                                                               'mask',
                                                               'audio_mask'],
                                        'native_output_names': ['latent'],
                                        'native_input_types': ['VIDEO', 'VAE', 'VAE', 'MASK', 'MASK'],
                                        'native_output_types': ['LATENT'],
                                        'native_input_optional': [False, False, False, False, False],
                                        'native_input_asset_kinds': None,
                                        'native_output_slots': None},
                       'metadata': {'schema_source': {'provider': '',
                                                      'path': None,
                                                      'cache_path': None,
                                                      'server_url': None,
                                                      'package': None,
                                                      'version': None,
                                                      'hash': None,
                                                      'confidence': 0.0},
                                    'provenance': 'untrusted_source'},
                       'widget_channels': {},
                       'none_input_fields': [],
                       'none_widget_fields': [],
                       'output_slot_names': {}},
 'basicscheduler': {'id': '105::9',
                    'uid': '105::9',
                    'class_type': 'BasicScheduler',
                    'native_ports': {'native_input_names': ['model'],
                                     'native_output_names': ['SIGMAS'],
                                     'native_input_types': ['MODEL'],
                                     'native_output_types': ['SIGMAS'],
                                     'native_input_optional': [False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['SIGMAS'],
                                 'output_types': ['SIGMAS'],
                                 'keep_defaults': ['denoise', 'scheduler', 'steps']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'basicguider': {'id': '105::16',
                 'uid': '105::16',
                 'class_type': 'BasicGuider',
                 'native_ports': {'native_input_names': ['model', 'conditioning'],
                                  'native_output_names': ['GUIDER'],
                                  'native_input_types': ['MODEL', 'CONDITIONING'],
                                  'native_output_types': ['GUIDER'],
                                  'native_input_optional': [False, False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['GUIDER'],
                              'output_types': ['GUIDER']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'lanpaint_samplercustomadvanced': {'id': '105::159',
                                    'uid': '105::159',
                                    'class_type': 'LanPaint_SamplerCustomAdvanced',
                                    'native_ports': {'native_input_names': ['noise',
                                                                            'guider',
                                                                            'sampler',
                                                                            'sigmas',
                                                                            'latent_image',
                                                                            'LanPaint_NumSteps'],
                                                     'native_output_names': ['output', 'denoised_output'],
                                                     'native_input_types': ['NOISE',
                                                                            'GUIDER',
                                                                            'SAMPLER',
                                                                            'SIGMAS',
                                                                            'LATENT',
                                                                            'INT'],
                                                     'native_output_types': ['LATENT', 'LATENT'],
                                                     'native_input_optional': [False,
                                                                               False,
                                                                               False,
                                                                               False,
                                                                               False,
                                                                               False],
                                                     'native_input_asset_kinds': None,
                                                     'native_output_slots': None},
                                    'metadata': {'schema_source': {'provider': 'widget_schema',
                                                                   'path': None,
                                                                   'cache_path': None,
                                                                   'server_url': None,
                                                                   'package': None,
                                                                   'version': None,
                                                                   'hash': None,
                                                                   'confidence': 0.3},
                                                 'provenance': 'untrusted_source',
                                                 'keep_defaults': ['LanPaint_Info',
                                                                   'LanPaint_Lambda',
                                                                   'LanPaint_NumSteps',
                                                                   'LanPaint_PromptMode',
                                                                   'LanPaint_StepSize',
                                                                   'unused_widget_5']},
                                    'widget_channels': {},
                                    'none_input_fields': [],
                                    'none_widget_fields': [],
                                    'output_slot_names': {}},
 'lanpaint_avdecode': {'id': '105::168',
                       'uid': '105::168',
                       'class_type': 'LanPaint_AVDecode',
                       'native_ports': {'native_input_names': ['samples',
                                                               'video',
                                                               'vae',
                                                               'audio_vae',
                                                               'mask',
                                                               'audio_mask'],
                                        'native_output_names': ['video', 'audio'],
                                        'native_input_types': ['LATENT',
                                                               'VIDEO',
                                                               'VAE',
                                                               'VAE',
                                                               'MASK',
                                                               'MASK'],
                                        'native_output_types': ['VIDEO', 'AUDIO'],
                                        'native_input_optional': [False, False, False, False, False, False],
                                        'native_input_asset_kinds': None,
                                        'native_output_slots': None},
                       'metadata': {'schema_source': {'provider': 'widget_schema',
                                                      'path': None,
                                                      'cache_path': None,
                                                      'server_url': None,
                                                      'package': None,
                                                      'version': None,
                                                      'hash': None,
                                                      'confidence': 0.3},
                                    'provenance': 'untrusted_source',
                                    'keep_defaults': ['audio_crossfade', 'blend_overlap']},
                       'widget_channels': {},
                       'none_input_fields': [],
                       'none_widget_fields': [],
                       'output_slot_names': {}},
 'savevideo': {'id': '92',
               'uid': '92',
               'class_type': 'SaveVideo',
               'native_ports': {'native_input_names': ['video'],
                                'native_output_names': ['video'],
                                'native_input_types': ['VIDEO'],
                                'native_output_types': ['VIDEO'],
                                'native_input_optional': [False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'keep_defaults': ['codec', 'filename_prefix', 'format']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}}}
HELPER_CUSTODY = [{'id': '171',
  'uid': '171',
  'class_type': 'PrimitiveInt',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': [],
                   'native_output_names': ['INT'],
                   'native_input_types': [],
                   'native_output_types': ['INT'],
                   'native_input_optional': [],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}},
 {'id': '105::111',
  'uid': '105::111',
  'class_type': 'PrimitiveFloat',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': ['value'],
                   'native_output_names': ['FLOAT'],
                   'native_input_types': ['FLOAT'],
                   'native_output_types': ['FLOAT'],
                   'native_input_optional': [False],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}},
 {'id': '105::146',
  'uid': '105::146',
  'class_type': 'Reroute',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': [None],
                   'native_output_names': [None],
                   'native_input_types': ['*'],
                   'native_output_types': ['VAE'],
                   'native_input_optional': [False],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}},
 {'id': '105::148',
  'uid': '105::148',
  'class_type': 'Reroute',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': [None],
                   'native_output_names': [None],
                   'native_input_types': ['*'],
                   'native_output_types': ['VAE'],
                   'native_input_optional': [False],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}}]

READY_METADATA = ReadyMetadata.build(
    capability='video',
    template_id='MiniMax_H3_AV_EncodeDecode_Inpaint',
    inputs=PUBLIC_INPUT_METADATA,
    requirements={'models': ['minimax_h3_audio_vae_fp32.safetensors', 'minimax_h3_fl2va_pruned_fp8_scaled.safetensors', 'minimax_h3_video_vae_fp16.safetensors', 'qwen3vl_32b_minimax_h3_int8_convrot.safetensors']},
    _native_subgraph_provenance={'source_sha256': 'bdd3dc3b8ada880291418a622778e6e0bac2072ecf93064898f0cacdbe295715', 'source_kind': 'comfyui_native_subgraph'},
    _native_subgraph_diagnostics=[{'kind': 'repaired_output_backlink', 'link_id': 199, 'node_id': '107', 'slot': 1}, {'kind': 'expanded_native_subgraph', 'instance_id': '105', 'definition': 'Image to Video (MiniMax H3)'}],
    provenance={'source_path': 'docs/handover/unified-workflow-integrity-20260909/assets/h3/MiniMax_H3_AV_EncodeDecode_Inpaint.json', 'source_id': 'MiniMax_H3_AV_EncodeDecode_Inpaint', 'source_type': 'api', 'source_workflow_path': 'docs/handover/unified-workflow-integrity-20260909/assets/h3/MiniMax_H3_AV_EncodeDecode_Inpaint.json', 'source_ref': 'docs/handover/unified-workflow-integrity-20260909/assets/h3/MiniMax_H3_AV_EncodeDecode_Inpaint.json', 'source_kind': 'raw_json', 'indexed_id': None, 'workflow_source_id': 'MiniMax_H3_AV_EncodeDecode_Inpaint', 'workflow_source_type': 'api', 'raw_workflow_shape': 'ui', 'source_hash': 'sha256:2dd64fe26c42281962e434841c458cc935b1d1858e83093b882bbaeb02dc3121', 'workflow_shape': {'nodes': 24, 'runtime_nodes': 20, 'helper_nodes': 4, 'edges': 29, 'inputs': 2, 'outputs': 1}, 'output_mode': 'scratchpad'},
)

def build() -> VibeWorkflow:
    """Build the workflow (auto-generated)."""
    wf = new_workflow(READY_METADATA, source_path=__file__, canonical_custody=CANONICAL_CUSTODY)

    resolutionselector = ResolutionSelector(
        aspect_ratio='16:9 (Widescreen)',
        megapixels=0.4,
        multiple=32,
    )

    markdownnote = raw_call('MarkdownNote')
    markdownnote_2 = raw_call('MarkdownNote')
    markdownnote_3 = raw_call('MarkdownNote')

    lanpaint_videomaskeditor = raw_call('LanPaint_VideoMaskEditor',
        video='Masked_LoadMe.mp4',
        keyframes='{"0":"lanpaint_kf_1786525157475_0.png","41":"lanpaint_kf_1786525157475_41.png","42":"lanpaint_kf_1786525157475_42.png","56":"lanpaint_kf_1786525157475_56.png","64":"lanpaint_kf_1786525157475_64.png","65":"lanpaint_kf_1786525157475_65.png","66":"lanpaint_kf_1786525157475_66.png","70":"lanpaint_kf_1786525157475_70.png","78":"lanpaint_kf_1786525157475_78.png","82":"lanpaint_kf_1786525157475_82.png","83":"lanpaint_kf_1786525157475_83.png","86":"lanpaint_kf_1786525157475_86.png","87":"lanpaint_kf_1786525157475_87.png","88":"lanpaint_kf_1786525157475_88.png","89":"lanpaint_kf_1786525157475_89.png","92":"lanpaint_kf_1786525157475_92.png","98":"lanpaint_kf_1786525157475_98.png","106":"lanpaint_kf_1786525157475_106.png","112":"lanpaint_kf_1786525157475_112.png","115":"lanpaint_kf_1786525157475_115.png","116":"lanpaint_kf_1786525157475_116.png","117":"lanpaint_kf_1786525157475_117.png","121":"lanpaint_kf_1786525157475_121.png","122":"lanpaint_kf_1786525157475_122.png","123":"lanpaint_kf_1786525157475_123.png"}',
        audio_mask='[{"start":3.7479933970546644,"end":5.161482918309433}]',
    )

    markdownnote_4 = raw_call('MarkdownNote')

    comfymathexpression = ComfyMathExpression(
        expression='max(5, round(a * 24)) + (5 - (max(5, round(a * 24)) % 17)) % 17',
        **{'values.a': 5},
    )

    # Loaders
    vaeloader = VAELoader(vae_name=VIDEO_VAE_NAME)
    cliploader = CLIPLoader(clip_name=CLIP_NAME, type='minimax', device='default')

    randomnoise = RandomNoise(
        noise_seed=DEFAULT_SEED,
        control_after_generate='randomize',
    )

    # Sampling
    ksamplerselect = KSamplerSelect(sampler_name='euler')
    vaeloader_2 = VAELoader(vae_name=AUDIO_VAE_NAME)
    unetloader = UNETLoader(unet_name=UNET_NAME, weight_dtype='default')

    minimaxh3imagetovideo = raw_call('MiniMaxH3ImageToVideo',
        prompt=DEFAULT_PROMPT,
        width=resolutionselector.out('width'),
        height=resolutionselector.out('height'),
        length=comfymathexpression.out('INT'),
        clip=cliploader.out('CLIP'),
        vae=vaeloader.out('VAE'),
    )

    lanpaint_avencode = raw_call('LanPaint_AVEncode',
        audio_mask=lanpaint_videomaskeditor.out(2),
        audio_vae=vaeloader_2.out('VAE'),
        mask=lanpaint_videomaskeditor.out(1),
        vae=vaeloader.out('VAE'),
        video=lanpaint_videomaskeditor.out(0),
    )

    basicscheduler = BasicScheduler(
        scheduler='simple',
        steps=20,
        denoise=1,
        model=unetloader.out('MODEL'),
    )

    basicguider = BasicGuider(
        conditioning=minimaxh3imagetovideo.out(0),
        model=unetloader.out('MODEL'),
    )

    lanpaint_samplercustomadvanced = raw_call('LanPaint_SamplerCustomAdvanced',
        LanPaint_NumSteps=5,
        LanPaint_Lambda=5,
        LanPaint_StepSize=0.2,
        LanPaint_PromptMode='Image First',
        LanPaint_Info='LanPaint Custom Sampler Adv.',
        guider=basicguider.out('GUIDER'),
        latent_image=lanpaint_avencode.out(0),
        noise=randomnoise.out('NOISE'),
        sampler=ksamplerselect.out('SAMPLER'),
        sigmas=basicscheduler.out('SIGMAS'),
    )

    lanpaint_avdecode = raw_call('LanPaint_AVDecode',
        blend_overlap=7,
        audio_crossfade=0.02,
        audio_mask=lanpaint_videomaskeditor.out(2),
        audio_vae=vaeloader_2.out('VAE'),
        mask=lanpaint_videomaskeditor.out(1),
        samples=lanpaint_samplercustomadvanced.out(0),
        vae=vaeloader.out('VAE'),
        video=lanpaint_videomaskeditor.out(0),
    )

    # Outputs
    savevideo = SaveVideo(
        filename_prefix='video/MiniMax_H3',
        format='auto',
        codec='auto',
        video=lanpaint_avdecode.out(0),
    )

    wf = wf.finalize(PUBLIC_INPUT_METADATA, canonical_outputs=[{'node': savevideo, 'output_type': 'SaveVideo', 'name': None, 'artifact_kind': None, 'mime_type': None, 'filename_prefix': None, 'expected_cardinality': None}], canonical_requirements={'models': ['minimax_h3_audio_vae_fp32.safetensors', 'minimax_h3_fl2va_pruned_fp8_scaled.safetensors', 'minimax_h3_video_vae_fp16.safetensors', 'qwen3vl_32b_minimax_h3_int8_convrot.safetensors'], 'custom_nodes': [], 'missing_models': [], 'missing_nodes': ['LanPaint_AVEncode'], 'unsupported': []}, canonical_custody=CANONICAL_CUSTODY, canonical_bindings={'resolutionselector': resolutionselector, 'markdownnote': markdownnote, 'markdownnote_2': markdownnote_2, 'markdownnote_3': markdownnote_3, 'lanpaint_videomaskeditor': lanpaint_videomaskeditor, 'markdownnote_4': markdownnote_4, 'comfymathexpression': comfymathexpression, 'vaeloader': vaeloader, 'cliploader': cliploader, 'randomnoise': randomnoise, 'ksamplerselect': ksamplerselect, 'vaeloader_2': vaeloader_2, 'unetloader': unetloader, 'minimaxh3imagetovideo': minimaxh3imagetovideo, 'lanpaint_avencode': lanpaint_avencode, 'basicscheduler': basicscheduler, 'basicguider': basicguider, 'lanpaint_samplercustomadvanced': lanpaint_samplercustomadvanced, 'lanpaint_avdecode': lanpaint_avdecode, 'savevideo': savevideo}, canonical_helpers=HELPER_CUSTODY)
    wf.strict_types = False
    return wf
