# vibecomfy: generated
# For hand-editing, run: python -m vibecomfy.cli copy-to-recipe <id>
# vibecomfy: surface=canonical
"""Auto-generated ready_template — use python -m vibecomfy.cli copy-to-recipe <id> for hand-editing."""
from __future__ import annotations

from vibecomfy.templates import InputSpec, ReadyMetadata, new_workflow, node as raw_call, ref
from vibecomfy.workflow import VibeWorkflow
from vibecomfy.nodes.core import BasicGuider, BasicScheduler, CLIPLoader, ComfyMathExpression, KSamplerSelect, RandomNoise, ResolutionSelector, SaveVideo, UNETLoader, VAELoader


AUDIO_VAE_NAME = 'minimax_h3_audio_vae_fp32.safetensors'
CLIP_NAME = 'qwen3vl_32b_minimax_h3_int8_convrot.safetensors'
DEFAULT_PROMPT = 'Edited H3 prompt: blue-hour dance with synchronized stereo audio.'
UNET_NAME = 'edited-minimax-h3.safetensors'
VIDEO_VAE_NAME = 'minimax_h3_video_vae_fp16.safetensors'
DEFAULT_SEED = 123


PUBLIC_INPUT_METADATA = {
    'model': InputSpec(node=ref('unetloader'), field='unet_name', default=None, infer_type=False),
    'steps': InputSpec(node=ref('basicscheduler'), field='steps', default=None, infer_type=False),
    'seed': InputSpec(node=ref('randomnoise'), field='noise_seed', default=DEFAULT_SEED, type='INT'),
}

CANONICAL_CUSTODY = {'resolutionselector': {'id': '115',
                        'uid': '115',
                        'class_type': 'ResolutionSelector',
                        'native_ports': {'native_input_names': [],
                                         'native_output_names': ['width', 'height'],
                                         'native_input_types': [],
                                         'native_output_types': ['INT', 'INT'],
                                         'native_input_optional': [],
                                         'native_input_asset_kinds': None,
                                         'native_output_slots': None},
                        'metadata': {'schema_source': {'provider': 'object_info_index',
                                                       'path': None,
                                                       'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                       'server_url': None,
                                                       'package': 'comfy_core',
                                                       'version': None,
                                                       'hash': None,
                                                       'confidence': 0.7},
                                     'provenance': 'untrusted_source',
                                     'output_names': ['width', 'height'],
                                     'output_types': ['INT', 'INT'],
                                     'keep_defaults': ['aspect_ratio', 'megapixels', 'multiple']},
                        'widget_channels': {},
                        'none_input_fields': [],
                        'none_widget_fields': [],
                        'output_slot_names': {}},
 'markdownnote': {'id': '116',
                  'uid': '116',
                  'class_type': 'MarkdownNote',
                  'native_ports': {'native_input_names': [],
                                   'native_output_names': [],
                                   'native_input_types': [],
                                   'native_output_types': [],
                                   'native_input_optional': [],
                                   'native_input_asset_kinds': None,
                                   'native_output_slots': None},
                  'metadata': {'schema_source': {'provider': 'widget_schema',
                                                 'path': None,
                                                 'cache_path': None,
                                                 'server_url': None,
                                                 'package': None,
                                                 'version': None,
                                                 'hash': None,
                                                 'confidence': 0.3},
                               'provenance': 'untrusted_source',
                               'keep_defaults': ['unused_widget_0']},
                  'widget_channels': {},
                  'none_input_fields': [],
                  'none_widget_fields': [],
                  'output_slot_names': {}},
 'markdownnote_2': {'id': '117',
                    'uid': '117',
                    'class_type': 'MarkdownNote',
                    'native_ports': {'native_input_names': [],
                                     'native_output_names': [],
                                     'native_input_types': [],
                                     'native_output_types': [],
                                     'native_input_optional': [],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'widget_schema',
                                                   'path': None,
                                                   'cache_path': None,
                                                   'server_url': None,
                                                   'package': None,
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.3},
                                 'provenance': 'untrusted_source',
                                 'keep_defaults': ['unused_widget_0']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'markdownnote_3': {'id': '118',
                    'uid': '118',
                    'class_type': 'MarkdownNote',
                    'native_ports': {'native_input_names': [],
                                     'native_output_names': [],
                                     'native_input_types': [],
                                     'native_output_types': [],
                                     'native_input_optional': [],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'widget_schema',
                                                   'path': None,
                                                   'cache_path': None,
                                                   'server_url': None,
                                                   'package': None,
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.3},
                                 'provenance': 'untrusted_source',
                                 'keep_defaults': ['unused_widget_0']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'lanpaint_videomaskeditor': {'id': '164',
                              'uid': '164',
                              'class_type': 'LanPaint_VideoMaskEditor',
                              'native_ports': {'native_input_names': [],
                                               'native_output_names': ['video', 'mask', 'audio_mask'],
                                               'native_input_types': [],
                                               'native_output_types': ['VIDEO', 'MASK', 'MASK'],
                                               'native_input_optional': [],
                                               'native_input_asset_kinds': None,
                                               'native_output_slots': None},
                              'metadata': {'schema_source': {'provider': 'widget_schema',
                                                             'path': None,
                                                             'cache_path': None,
                                                             'server_url': None,
                                                             'package': None,
                                                             'version': None,
                                                             'hash': None,
                                                             'confidence': 0.3},
                                           'provenance': 'untrusted_source',
                                           'keep_defaults': ['audio_mask',
                                                             'keyframes',
                                                             'unused_widget_3',
                                                             'unused_widget_4',
                                                             'video']},
                              'widget_channels': {},
                              'none_input_fields': [],
                              'none_widget_fields': [],
                              'output_slot_names': {}},
 'markdownnote_4': {'id': '170',
                    'uid': '170',
                    'class_type': 'MarkdownNote',
                    'native_ports': {'native_input_names': [],
                                     'native_output_names': [],
                                     'native_input_types': [],
                                     'native_output_types': [],
                                     'native_input_optional': [],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'widget_schema',
                                                   'path': None,
                                                   'cache_path': None,
                                                   'server_url': None,
                                                   'package': None,
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.3},
                                 'provenance': 'untrusted_source',
                                 'keep_defaults': ['unused_widget_0']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'comfymathexpression': {'id': '105::107',
                         'uid': '105::107',
                         'class_type': 'ComfyMathExpression',
                         'native_ports': {'native_input_names': ['values.a', 'values.b'],
                                          'native_output_names': ['FLOAT', 'INT', 'BOOL'],
                                          'native_input_types': ['FLOAT,INT,BOOLEAN', 'FLOAT,INT,BOOLEAN'],
                                          'native_output_types': ['FLOAT', 'INT', 'BOOLEAN'],
                                          'native_input_optional': [False, True],
                                          'native_input_asset_kinds': None,
                                          'native_output_slots': None},
                         'metadata': {'schema_source': {'provider': 'object_info_index',
                                                        'path': None,
                                                        'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                        'server_url': None,
                                                        'package': 'comfy_core',
                                                        'version': None,
                                                        'hash': None,
                                                        'confidence': 0.7},
                                      'provenance': 'untrusted_source',
                                      'output_names': ['FLOAT', 'INT', 'BOOL'],
                                      'output_types': ['FLOAT', 'INT', 'BOOLEAN'],
                                      'keep_defaults': ['expression']},
                         'widget_channels': {},
                         'none_input_fields': [],
                         'none_widget_fields': [],
                         'output_slot_names': {}},
 'vaeloader': {'id': '105::11',
               'uid': '105::11',
               'class_type': 'VAELoader',
               'native_ports': {'native_input_names': ['vae_name'],
                                'native_output_names': ['VAE'],
                                'native_input_types': ['COMBO'],
                                'native_output_types': ['VAE'],
                                'native_input_optional': [False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'output_names': ['VAE'],
                            'output_types': ['VAE'],
                            'keep_defaults': ['vae_name']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}},
 'cliploader': {'id': '105::13',
                'uid': '105::13',
                'class_type': 'CLIPLoader',
                'native_ports': {'native_input_names': ['clip_name'],
                                 'native_output_names': ['CLIP'],
                                 'native_input_types': ['COMBO'],
                                 'native_output_types': ['CLIP'],
                                 'native_input_optional': [False],
                                 'native_input_asset_kinds': None,
                                 'native_output_slots': None},
                'metadata': {'schema_source': {'provider': 'object_info_index',
                                               'path': None,
                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                               'server_url': None,
                                               'package': 'comfy_core',
                                               'version': None,
                                               'hash': None,
                                               'confidence': 0.7},
                             'provenance': 'untrusted_source',
                             'output_names': ['CLIP'],
                             'output_types': ['CLIP'],
                             'keep_defaults': ['clip_name', 'device', 'type']},
                'widget_channels': {},
                'none_input_fields': [],
                'none_widget_fields': [],
                'output_slot_names': {}},
 'randomnoise': {'id': '105::15',
                 'uid': '105::15',
                 'class_type': 'RandomNoise',
                 'native_ports': {'native_input_names': ['noise_seed'],
                                  'native_output_names': ['NOISE'],
                                  'native_input_types': ['INT'],
                                  'native_output_types': ['NOISE'],
                                  'native_input_optional': [False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['NOISE'],
                              'output_types': ['NOISE'],
                              'keep_defaults': ['control_after_generate']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'ksamplerselect': {'id': '105::17',
                    'uid': '105::17',
                    'class_type': 'KSamplerSelect',
                    'native_ports': {'native_input_names': [],
                                     'native_output_names': ['SAMPLER'],
                                     'native_input_types': [],
                                     'native_output_types': ['SAMPLER'],
                                     'native_input_optional': [],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['SAMPLER'],
                                 'output_types': ['SAMPLER'],
                                 'keep_defaults': ['sampler_name']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'vaeloader_2': {'id': '105::24',
                 'uid': '105::24',
                 'class_type': 'VAELoader',
                 'native_ports': {'native_input_names': ['vae_name'],
                                  'native_output_names': ['VAE'],
                                  'native_input_types': ['COMBO'],
                                  'native_output_types': ['VAE'],
                                  'native_input_optional': [False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['VAE'],
                              'output_types': ['VAE'],
                              'keep_defaults': ['vae_name']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'unetloader': {'id': '105::6',
                'uid': '105::6',
                'class_type': 'UNETLoader',
                'native_ports': {'native_input_names': ['unet_name'],
                                 'native_output_names': ['MODEL'],
                                 'native_input_types': ['COMBO'],
                                 'native_output_types': ['MODEL'],
                                 'native_input_optional': [False],
                                 'native_input_asset_kinds': None,
                                 'native_output_slots': None},
                'metadata': {'schema_source': {'provider': 'object_info_index',
                                               'path': None,
                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                               'server_url': None,
                                               'package': 'comfy_core',
                                               'version': None,
                                               'hash': None,
                                               'confidence': 0.7},
                             'provenance': 'untrusted_source',
                             'output_names': ['MODEL'],
                             'output_types': ['MODEL'],
                             'keep_defaults': ['unet_name', 'weight_dtype']},
                'widget_channels': {},
                'none_input_fields': [],
                'none_widget_fields': [],
                'output_slot_names': {}},
 'minimaxh3imagetovideo': {'id': '105::104',
                           'uid': '105::104',
                           'class_type': 'MiniMaxH3ImageToVideo',
                           'native_ports': {'native_input_names': ['clip',
                                                                   'vae',
                                                                   'first_frame',
                                                                   'last_frame',
                                                                   'prompt',
                                                                   'width',
                                                                   'height',
                                                                   'length'],
                                            'native_output_names': ['positive', 'LATENT'],
                                            'native_input_types': ['CLIP',
                                                                   'VAE',
                                                                   'IMAGE',
                                                                   'IMAGE',
                                                                   'STRING',
                                                                   'INT',
                                                                   'INT',
                                                                   'INT'],
                                            'native_output_types': ['CONDITIONING', 'LATENT'],
                                            'native_input_optional': [False,
                                                                      False,
                                                                      True,
                                                                      True,
                                                                      False,
                                                                      False,
                                                                      False,
                                                                      False],
                                            'native_input_asset_kinds': None,
                                            'native_output_slots': None},
                           'metadata': {'schema_source': {'provider': 'widget_schema',
                                                          'path': None,
                                                          'cache_path': None,
                                                          'server_url': None,
                                                          'package': None,
                                                          'version': None,
                                                          'hash': None,
                                                          'confidence': 0.3},
                                        'provenance': 'untrusted_source',
                                        'keep_defaults': ['prompt']},
                           'widget_channels': {},
                           'none_input_fields': [],
                           'none_widget_fields': [],
                           'output_slot_names': {}},
 'lanpaint_avencode': {'id': '105::166',
                       'uid': '105::166',
                       'class_type': 'LanPaint_AVEncode',
                       'native_ports': {'native_input_names': ['video',
                                                               'vae',
                                                               'audio_vae',
                                                               'mask',
                                                               'audio_mask'],
                                        'native_output_names': ['latent'],
                                        'native_input_types': ['VIDEO', 'VAE', 'VAE', 'MASK', 'MASK'],
                                        'native_output_types': ['LATENT'],
                                        'native_input_optional': [False, False, False, False, False],
                                        'native_input_asset_kinds': None,
                                        'native_output_slots': None},
                       'metadata': {'schema_source': {'provider': '',
                                                      'path': None,
                                                      'cache_path': None,
                                                      'server_url': None,
                                                      'package': None,
                                                      'version': None,
                                                      'hash': None,
                                                      'confidence': 0.0},
                                    'provenance': 'untrusted_source'},
                       'widget_channels': {},
                       'none_input_fields': [],
                       'none_widget_fields': [],
                       'output_slot_names': {}},
 'basicscheduler': {'id': '105::9',
                    'uid': '105::9',
                    'class_type': 'BasicScheduler',
                    'native_ports': {'native_input_names': ['model'],
                                     'native_output_names': ['SIGMAS'],
                                     'native_input_types': ['MODEL'],
                                     'native_output_types': ['SIGMAS'],
                                     'native_input_optional': [False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['SIGMAS'],
                                 'output_types': ['SIGMAS'],
                                 'keep_defaults': ['denoise', 'scheduler', 'steps']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'basicguider': {'id': '105::16',
                 'uid': '105::16',
                 'class_type': 'BasicGuider',
                 'native_ports': {'native_input_names': ['model', 'conditioning'],
                                  'native_output_names': ['GUIDER'],
                                  'native_input_types': ['MODEL', 'CONDITIONING'],
                                  'native_output_types': ['GUIDER'],
                                  'native_input_optional': [False, False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['GUIDER'],
                              'output_types': ['GUIDER']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'lanpaint_samplercustomadvanced': {'id': '105::159',
                                    'uid': '105::159',
                                    'class_type': 'LanPaint_SamplerCustomAdvanced',
                                    'native_ports': {'native_input_names': ['noise',
                                                                            'guider',
                                                                            'sampler',
                                                                            'sigmas',
                                                                            'latent_image',
                                                                            'LanPaint_NumSteps'],
                                                     'native_output_names': ['output', 'denoised_output'],
                                                     'native_input_types': ['NOISE',
                                                                            'GUIDER',
                                                                            'SAMPLER',
                                                                            'SIGMAS',
                                                                            'LATENT',
                                                                            'INT'],
                                                     'native_output_types': ['LATENT', 'LATENT'],
                                                     'native_input_optional': [False,
                                                                               False,
                                                                               False,
                                                                               False,
                                                                               False,
                                                                               False],
                                                     'native_input_asset_kinds': None,
                                                     'native_output_slots': None},
                                    'metadata': {'schema_source': {'provider': 'widget_schema',
                                                                   'path': None,
                                                                   'cache_path': None,
                                                                   'server_url': None,
                                                                   'package': None,
                                                                   'version': None,
                                                                   'hash': None,
                                                                   'confidence': 0.3},
                                                 'provenance': 'untrusted_source',
                                                 'keep_defaults': ['LanPaint_Info',
                                                                   'LanPaint_Lambda',
                                                                   'LanPaint_NumSteps',
                                                                   'LanPaint_PromptMode',
                                                                   'LanPaint_StepSize',
                                                                   'unused_widget_5']},
                                    'widget_channels': {},
                                    'none_input_fields': [],
                                    'none_widget_fields': [],
                                    'output_slot_names': {}},
 'lanpaint_avdecode': {'id': '105::168',
                       'uid': '105::168',
                       'class_type': 'LanPaint_AVDecode',
                       'native_ports': {'native_input_names': ['samples',
                                                               'video',
                                                               'vae',
                                                               'audio_vae',
                                                               'mask',
                                                               'audio_mask'],
                                        'native_output_names': ['video', 'audio'],
                                        'native_input_types': ['LATENT',
                                                               'VIDEO',
                                                               'VAE',
                                                               'VAE',
                                                               'MASK',
                                                               'MASK'],
                                        'native_output_types': ['VIDEO', 'AUDIO'],
                                        'native_input_optional': [False, False, False, False, False, False],
                                        'native_input_asset_kinds': None,
                                        'native_output_slots': None},
                       'metadata': {'schema_source': {'provider': 'widget_schema',
                                                      'path': None,
                                                      'cache_path': None,
                                                      'server_url': None,
                                                      'package': None,
                                                      'version': None,
                                                      'hash': None,
                                                      'confidence': 0.3},
                                    'provenance': 'untrusted_source',
                                    'keep_defaults': ['audio_crossfade', 'blend_overlap']},
                       'widget_channels': {},
                       'none_input_fields': [],
                       'none_widget_fields': [],
                       'output_slot_names': {}},
 'savevideo': {'id': '92',
               'uid': '92',
               'class_type': 'SaveVideo',
               'native_ports': {'native_input_names': ['video'],
                                'native_output_names': ['video'],
                                'native_input_types': ['VIDEO'],
                                'native_output_types': ['VIDEO'],
                                'native_input_optional': [False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'keep_defaults': ['codec', 'filename_prefix', 'format']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}}}
HELPER_CUSTODY = [{'id': '171',
  'uid': '171',
  'class_type': 'PrimitiveInt',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': [],
                   'native_output_names': ['INT'],
                   'native_input_types': [],
                   'native_output_types': ['INT'],
                   'native_input_optional': [],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}},
 {'id': '105::111',
  'uid': '105::111',
  'class_type': 'PrimitiveFloat',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': ['value'],
                   'native_output_names': ['FLOAT'],
                   'native_input_types': ['FLOAT'],
                   'native_output_types': ['FLOAT'],
                   'native_input_optional': [False],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}},
 {'id': '105::146',
  'uid': '105::146',
  'class_type': 'Reroute',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': [None],
                   'native_output_names': [None],
                   'native_input_types': ['*'],
                   'native_output_types': ['VAE'],
                   'native_input_optional': [False],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}},
 {'id': '105::148',
  'uid': '105::148',
  'class_type': 'Reroute',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': [None],
                   'native_output_names': [None],
                   'native_input_types': ['*'],
                   'native_output_types': ['VAE'],
                   'native_input_optional': [False],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}}]

READY_METADATA = ReadyMetadata.build(
    capability='video',
    template_id='MiniMax_H3_AV_EncodeDecode_Inpaint',
    inputs=PUBLIC_INPUT_METADATA,
    requirements={'models': ['minimax_h3_audio_vae_fp32.safetensors', 'minimax_h3_fl2va_pruned_fp8_scaled.safetensors', 'minimax_h3_video_vae_fp16.safetensors', 'qwen3vl_32b_minimax_h3_int8_convrot.safetensors']},
    _native_subgraph_provenance={'source_sha256': 'bdd3dc3b8ada880291418a622778e6e0bac2072ecf93064898f0cacdbe295715', 'source_kind': 'comfyui_native_subgraph'},
    _native_subgraph_diagnostics=[{'kind': 'repaired_output_backlink', 'link_id': 199, 'node_id': '107', 'slot': 1}, {'kind': 'expanded_native_subgraph', 'instance_id': '105', 'definition': 'Image to Video (MiniMax H3)'}],
    provenance={'source_path': 'docs/handover/unified-workflow-integrity-20260909/assets/h3/MiniMax_H3_AV_EncodeDecode_Inpaint.json', 'source_id': 'MiniMax_H3_AV_EncodeDecode_Inpaint', 'source_type': 'api', 'source_workflow_path': 'docs/handover/unified-workflow-integrity-20260909/assets/h3/MiniMax_H3_AV_EncodeDecode_Inpaint.json', 'source_ref': 'docs/handover/unified-workflow-integrity-20260909/assets/h3/MiniMax_H3_AV_EncodeDecode_Inpaint.json', 'source_kind': 'raw_json', 'indexed_id': None, 'workflow_source_id': 'MiniMax_H3_AV_EncodeDecode_Inpaint', 'workflow_source_type': 'api', 'raw_workflow_shape': 'ui', 'source_hash': 'sha256:2dd64fe26c42281962e434841c458cc935b1d1858e83093b882bbaeb02dc3121', 'workflow_shape': {'nodes': 24, 'runtime_nodes': 20, 'helper_nodes': 4, 'edges': 29, 'inputs': 2, 'outputs': 1}, 'output_mode': 'scratchpad'},
)

def build() -> VibeWorkflow:
    """Build the workflow (auto-generated)."""
    wf = new_workflow(READY_METADATA, source_path=__file__, canonical_custody=CANONICAL_CUSTODY)

    resolutionselector = ResolutionSelector(
        aspect_ratio='16:9 (Widescreen)',
        megapixels=0.4,
        multiple=32,
    )

    markdownnote = raw_call('MarkdownNote')
    markdownnote_2 = raw_call('MarkdownNote')
    markdownnote_3 = raw_call('MarkdownNote')

    lanpaint_videomaskeditor = raw_call('LanPaint_VideoMaskEditor',
        video='edited-source.mp4',
        keyframes='{"0":"edited-start.png","42":"edited-mid.png"}',
        audio_mask='[{"start":1.25,"end":2.75}]',
    )

    markdownnote_4 = raw_call('MarkdownNote')

    comfymathexpression = ComfyMathExpression(
        expression='max(5, round(a * 24)) + (5 - (max(5, round(a * 24)) % 17)) % 17',
        **{'values.a': 7},
    )

    # Loaders
    vaeloader = VAELoader(vae_name=VIDEO_VAE_NAME)
    cliploader = CLIPLoader(clip_name=CLIP_NAME, type='minimax', device='default')

    randomnoise = RandomNoise(
        noise_seed=DEFAULT_SEED,
        control_after_generate='randomize',
    )

    # Sampling
    ksamplerselect = KSamplerSelect(sampler_name='euler')
    vaeloader_2 = VAELoader(vae_name=AUDIO_VAE_NAME)
    unetloader = UNETLoader(unet_name=UNET_NAME, weight_dtype='default')

    minimaxh3imagetovideo = raw_call('MiniMaxH3ImageToVideo',
        prompt=DEFAULT_PROMPT,
        width=resolutionselector.out('width'),
        height=resolutionselector.out('height'),
        length=comfymathexpression.out('INT'),
        clip=cliploader.out('CLIP'),
        vae=vaeloader.out('VAE'),
    )

    lanpaint_avencode = raw_call('LanPaint_AVEncode',
        audio_mask=lanpaint_videomaskeditor.out(2),
        audio_vae=vaeloader_2.out('VAE'),
        mask=lanpaint_videomaskeditor.out(1),
        vae=vaeloader.out('VAE'),
        video=lanpaint_videomaskeditor.out(0),
    )

    basicscheduler = BasicScheduler(
        scheduler='simple',
        steps=31,
        denoise=1,
        model=unetloader.out('MODEL'),
    )

    basicguider = BasicGuider(
        conditioning=minimaxh3imagetovideo.out(0),
        model=unetloader.out('MODEL'),
    )

    lanpaint_samplercustomadvanced = raw_call('LanPaint_SamplerCustomAdvanced',
        LanPaint_NumSteps=9,
        LanPaint_Lambda=5,
        LanPaint_StepSize=0.2,
        LanPaint_PromptMode='Image First',
        LanPaint_Info='LanPaint Custom Sampler Adv.',
        guider=basicguider.out('GUIDER'),
        latent_image=lanpaint_avencode.out(0),
        noise=randomnoise.out('NOISE'),
        sampler=ksamplerselect.out('SAMPLER'),
        sigmas=basicscheduler.out('SIGMAS'),
    )

    lanpaint_avdecode = raw_call('LanPaint_AVDecode',
        blend_overlap=7,
        audio_crossfade=0.02,
        audio_mask=lanpaint_videomaskeditor.out(2),
        audio_vae=vaeloader_2.out('VAE'),
        mask=lanpaint_videomaskeditor.out(1),
        samples=lanpaint_samplercustomadvanced.out(0),
        vae=vaeloader.out('VAE'),
        video=lanpaint_videomaskeditor.out(0),
    )

    # Outputs
    savevideo = SaveVideo(
        filename_prefix='video/MiniMax_H3',
        format='auto',
        codec='auto',
        video=lanpaint_avdecode.out(0),
    )

    wf = wf.finalize(PUBLIC_INPUT_METADATA, canonical_outputs=[{'node': savevideo, 'output_type': 'SaveVideo', 'name': None, 'artifact_kind': None, 'mime_type': None, 'filename_prefix': None, 'expected_cardinality': None}], canonical_requirements={'models': ['minimax_h3_audio_vae_fp32.safetensors', 'minimax_h3_fl2va_pruned_fp8_scaled.safetensors', 'minimax_h3_video_vae_fp16.safetensors', 'qwen3vl_32b_minimax_h3_int8_convrot.safetensors'], 'custom_nodes': [], 'missing_models': [], 'missing_nodes': ['LanPaint_AVEncode'], 'unsupported': []}, canonical_custody=CANONICAL_CUSTODY, canonical_bindings={'resolutionselector': resolutionselector, 'markdownnote': markdownnote, 'markdownnote_2': markdownnote_2, 'markdownnote_3': markdownnote_3, 'lanpaint_videomaskeditor': lanpaint_videomaskeditor, 'markdownnote_4': markdownnote_4, 'comfymathexpression': comfymathexpression, 'vaeloader': vaeloader, 'cliploader': cliploader, 'randomnoise': randomnoise, 'ksamplerselect': ksamplerselect, 'vaeloader_2': vaeloader_2, 'unetloader': unetloader, 'minimaxh3imagetovideo': minimaxh3imagetovideo, 'lanpaint_avencode': lanpaint_avencode, 'basicscheduler': basicscheduler, 'basicguider': basicguider, 'lanpaint_samplercustomadvanced': lanpaint_samplercustomadvanced, 'lanpaint_avdecode': lanpaint_avdecode, 'savevideo': savevideo}, canonical_helpers=HELPER_CUSTODY)
    wf.strict_types = False
    return wf
