# vibecomfy: generated
# For hand-editing, run: python -m vibecomfy.cli copy-to-recipe <id>
# vibecomfy: surface=canonical
"""Auto-generated ready_template — use python -m vibecomfy.cli copy-to-recipe <id> for hand-editing."""
from __future__ import annotations

from vibecomfy.templates import InputSpec, ReadyMetadata, new_workflow, node as raw_call, ref
from vibecomfy.workflow import VibeWorkflow
from vibecomfy.nodes.core import CLIPLoader, CLIPTextEncode, CLIPVisionEncode, CLIPVisionLoader, CreateVideo, KSampler, LoadImage, ModelSamplingSD3, SaveVideo, UNETLoader, VAEDecode, VAELoader, WanImageToVideo


CLIP_NAME = 'umt5_xxl_fp8_e4m3fn_scaled.safetensors'
CLIP_NAME_2 = 'clip_vision_h.safetensors'
DEFAULT_FPS = 16
DEFAULT_FRAMES = 33
DEFAULT_PROMPT = 'a cute anime girl with massive fennec ears and a big fluffy tail wearing a maid outfit turning around'
DEFAULT_PROMPT_2 = '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'
DEFAULT_SEED = 987948718394761
GUIDE_STRENGTH = 6
UNET_NAME = 'wan2.1_i2v_480p_14B_fp16.safetensors'
VAE_NAME = 'wan_2.1_vae.safetensors'


PUBLIC_INPUT_METADATA = {
    'model': InputSpec(node=ref('unetloader'), field='unet_name', default=None, infer_type=False),
    'prompt': InputSpec(node=ref('cliptextencode'), field='text', default=None, infer_type=False),
    'seed': InputSpec(node=ref('ksampler'), field='seed', default=None, infer_type=False),
    'steps': InputSpec(node=ref('ksampler'), field='steps', default=None, infer_type=False),
}

CANONICAL_CUSTODY = {'unetloader': {'id': '37',
                'uid': '37',
                'class_type': 'UNETLoader',
                'native_ports': {'native_input_names': [],
                                 'native_output_names': ['MODEL'],
                                 'native_input_types': [],
                                 'native_output_types': ['MODEL'],
                                 'native_input_optional': [],
                                 'native_input_asset_kinds': None,
                                 'native_output_slots': None},
                'metadata': {'schema_source': {'provider': 'object_info_index',
                                               'path': None,
                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                               'server_url': None,
                                               'package': 'comfy_core',
                                               'version': None,
                                               'hash': None,
                                               'confidence': 0.7},
                             'provenance': 'untrusted_source',
                             'output_names': ['MODEL'],
                             'output_types': ['MODEL'],
                             'keep_defaults': ['unet_name', 'weight_dtype']},
                'widget_channels': {},
                'none_input_fields': [],
                'none_widget_fields': [],
                'output_slot_names': {}},
 'cliploader': {'id': '38',
                'uid': '38',
                'class_type': 'CLIPLoader',
                'native_ports': {'native_input_names': [],
                                 'native_output_names': ['CLIP'],
                                 'native_input_types': [],
                                 'native_output_types': ['CLIP'],
                                 'native_input_optional': [],
                                 'native_input_asset_kinds': None,
                                 'native_output_slots': None},
                'metadata': {'schema_source': {'provider': 'object_info_index',
                                               'path': None,
                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                               'server_url': None,
                                               'package': 'comfy_core',
                                               'version': None,
                                               'hash': None,
                                               'confidence': 0.7},
                             'provenance': 'untrusted_source',
                             'output_names': ['CLIP'],
                             'output_types': ['CLIP'],
                             'keep_defaults': ['clip_name', 'device', 'type']},
                'widget_channels': {},
                'none_input_fields': [],
                'none_widget_fields': [],
                'output_slot_names': {}},
 'vaeloader': {'id': '39',
               'uid': '39',
               'class_type': 'VAELoader',
               'native_ports': {'native_input_names': [],
                                'native_output_names': ['VAE'],
                                'native_input_types': [],
                                'native_output_types': ['VAE'],
                                'native_input_optional': [],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'output_names': ['VAE'],
                            'output_types': ['VAE'],
                            'keep_defaults': ['vae_name']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}},
 'clipvisionloader': {'id': '49',
                      'uid': '49',
                      'class_type': 'CLIPVisionLoader',
                      'native_ports': {'native_input_names': [],
                                       'native_output_names': ['CLIP_VISION'],
                                       'native_input_types': [],
                                       'native_output_types': ['CLIP_VISION'],
                                       'native_input_optional': [],
                                       'native_input_asset_kinds': None,
                                       'native_output_slots': None},
                      'metadata': {'schema_source': {'provider': 'object_info_index',
                                                     'path': None,
                                                     'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                     'server_url': None,
                                                     'package': 'comfy_core',
                                                     'version': None,
                                                     'hash': None,
                                                     'confidence': 0.7},
                                   'provenance': 'untrusted_source',
                                   'output_names': ['CLIP_VISION'],
                                   'output_types': ['CLIP_VISION'],
                                   'keep_defaults': ['clip_name']},
                      'widget_channels': {},
                      'none_input_fields': [],
                      'none_widget_fields': [],
                      'output_slot_names': {}},
 'loadimage': {'id': '52',
               'uid': '52',
               'class_type': 'LoadImage',
               'native_ports': {'native_input_names': [],
                                'native_output_names': ['IMAGE', 'MASK'],
                                'native_input_types': [],
                                'native_output_types': ['IMAGE', 'MASK'],
                                'native_input_optional': [],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'output_names': ['IMAGE', 'MASK'],
                            'output_types': ['IMAGE', 'MASK'],
                            'keep_defaults': ['image', 'unused_widget_1']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}},
 'markdownnote': {'id': '57',
                  'uid': '57',
                  'class_type': 'MarkdownNote',
                  'native_ports': {'native_input_names': [],
                                   'native_output_names': [],
                                   'native_input_types': [],
                                   'native_output_types': [],
                                   'native_input_optional': [],
                                   'native_input_asset_kinds': None,
                                   'native_output_slots': None},
                  'metadata': {'schema_source': {'provider': 'widget_schema',
                                                 'path': None,
                                                 'cache_path': None,
                                                 'server_url': None,
                                                 'package': None,
                                                 'version': None,
                                                 'hash': None,
                                                 'confidence': 0.3},
                               'provenance': 'untrusted_source',
                               'keep_defaults': ['unused_widget_0']},
                  'widget_channels': {},
                  'none_input_fields': [],
                  'none_widget_fields': [],
                  'output_slot_names': {}},
 'cliptextencode': {'id': '6',
                    'uid': '6',
                    'class_type': 'CLIPTextEncode',
                    'native_ports': {'native_input_names': ['clip'],
                                     'native_output_names': ['CONDITIONING'],
                                     'native_input_types': ['CLIP'],
                                     'native_output_types': ['CONDITIONING'],
                                     'native_input_optional': [False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['CONDITIONING'],
                                 'output_types': ['CONDITIONING'],
                                 'keep_defaults': ['text']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'cliptextencode_2': {'id': '7',
                      'uid': '7',
                      'class_type': 'CLIPTextEncode',
                      'native_ports': {'native_input_names': ['clip'],
                                       'native_output_names': ['CONDITIONING'],
                                       'native_input_types': ['CLIP'],
                                       'native_output_types': ['CONDITIONING'],
                                       'native_input_optional': [False],
                                       'native_input_asset_kinds': None,
                                       'native_output_slots': None},
                      'metadata': {'schema_source': {'provider': 'object_info_index',
                                                     'path': None,
                                                     'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                     'server_url': None,
                                                     'package': 'comfy_core',
                                                     'version': None,
                                                     'hash': None,
                                                     'confidence': 0.7},
                                   'provenance': 'untrusted_source',
                                   'output_names': ['CONDITIONING'],
                                   'output_types': ['CONDITIONING'],
                                   'keep_defaults': ['text']},
                      'widget_channels': {},
                      'none_input_fields': [],
                      'none_widget_fields': [],
                      'output_slot_names': {}},
 'clipvisionencode': {'id': '51',
                      'uid': '51',
                      'class_type': 'CLIPVisionEncode',
                      'native_ports': {'native_input_names': ['clip_vision', 'image'],
                                       'native_output_names': ['CLIP_VISION_OUTPUT'],
                                       'native_input_types': ['CLIP_VISION', 'IMAGE'],
                                       'native_output_types': ['CLIP_VISION_OUTPUT'],
                                       'native_input_optional': [False, False],
                                       'native_input_asset_kinds': None,
                                       'native_output_slots': None},
                      'metadata': {'schema_source': {'provider': 'object_info_index',
                                                     'path': None,
                                                     'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                     'server_url': None,
                                                     'package': 'comfy_core',
                                                     'version': None,
                                                     'hash': None,
                                                     'confidence': 0.7},
                                   'provenance': 'untrusted_source',
                                   'output_names': ['CLIP_VISION_OUTPUT'],
                                   'output_types': ['CLIP_VISION_OUTPUT'],
                                   'keep_defaults': ['crop']},
                      'widget_channels': {},
                      'none_input_fields': [],
                      'none_widget_fields': [],
                      'output_slot_names': {}},
 'modelsamplingsd3': {'id': '54',
                      'uid': '54',
                      'class_type': 'ModelSamplingSD3',
                      'native_ports': {'native_input_names': ['model'],
                                       'native_output_names': ['MODEL'],
                                       'native_input_types': ['MODEL'],
                                       'native_output_types': ['MODEL'],
                                       'native_input_optional': [False],
                                       'native_input_asset_kinds': None,
                                       'native_output_slots': None},
                      'metadata': {'schema_source': {'provider': 'object_info_index',
                                                     'path': None,
                                                     'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                     'server_url': None,
                                                     'package': 'comfy_core',
                                                     'version': None,
                                                     'hash': None,
                                                     'confidence': 0.7},
                                   'provenance': 'untrusted_source',
                                   'output_names': ['MODEL'],
                                   'output_types': ['MODEL'],
                                   'keep_defaults': ['shift']},
                      'widget_channels': {},
                      'none_input_fields': [],
                      'none_widget_fields': [],
                      'output_slot_names': {}},
 'wanimagetovideo': {'id': '50',
                     'uid': '50',
                     'class_type': 'WanImageToVideo',
                     'native_ports': {'native_input_names': ['positive',
                                                             'negative',
                                                             'vae',
                                                             'clip_vision_output',
                                                             'start_image'],
                                      'native_output_names': ['positive', 'negative', 'latent'],
                                      'native_input_types': ['CONDITIONING',
                                                             'CONDITIONING',
                                                             'VAE',
                                                             'CLIP_VISION_OUTPUT',
                                                             'IMAGE'],
                                      'native_output_types': ['CONDITIONING', 'CONDITIONING', 'LATENT'],
                                      'native_input_optional': [False, False, False, True, True],
                                      'native_input_asset_kinds': None,
                                      'native_output_slots': None},
                     'metadata': {'schema_source': {'provider': 'object_info_index',
                                                    'path': None,
                                                    'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                    'server_url': None,
                                                    'package': 'comfy_core',
                                                    'version': None,
                                                    'hash': None,
                                                    'confidence': 0.7},
                                  'provenance': 'untrusted_source',
                                  'output_names': ['positive', 'negative', 'latent'],
                                  'output_types': ['CONDITIONING', 'CONDITIONING', 'LATENT'],
                                  'keep_defaults': ['batch_size', 'height', 'length', 'width']},
                     'widget_channels': {},
                     'none_input_fields': [],
                     'none_widget_fields': [],
                     'output_slot_names': {}},
 'ksampler': {'id': '3',
              'uid': '3',
              'class_type': 'KSampler',
              'native_ports': {'native_input_names': ['model', 'positive', 'negative', 'latent_image'],
                               'native_output_names': ['LATENT'],
                               'native_input_types': ['MODEL', 'CONDITIONING', 'CONDITIONING', 'LATENT'],
                               'native_output_types': ['LATENT'],
                               'native_input_optional': [False, False, False, False],
                               'native_input_asset_kinds': None,
                               'native_output_slots': None},
              'metadata': {'schema_source': {'provider': 'object_info_index',
                                             'path': None,
                                             'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                             'server_url': None,
                                             'package': 'comfy_core',
                                             'version': None,
                                             'hash': None,
                                             'confidence': 0.7},
                           'provenance': 'untrusted_source',
                           'output_names': ['LATENT'],
                           'output_types': ['LATENT'],
                           'keep_defaults': ['cfg',
                                             'control_after_generate',
                                             'denoise',
                                             'sampler_name',
                                             'scheduler',
                                             'seed',
                                             'steps']},
              'widget_channels': {},
              'none_input_fields': [],
              'none_widget_fields': [],
              'output_slot_names': {}},
 'vaedecode': {'id': '8',
               'uid': '8',
               'class_type': 'VAEDecode',
               'native_ports': {'native_input_names': ['samples', 'vae'],
                                'native_output_names': ['IMAGE'],
                                'native_input_types': ['LATENT', 'VAE'],
                                'native_output_types': ['IMAGE'],
                                'native_input_optional': [False, False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'output_names': ['IMAGE'],
                            'output_types': ['IMAGE']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}},
 'createvideo': {'id': '55',
                 'uid': '55',
                 'class_type': 'CreateVideo',
                 'native_ports': {'native_input_names': ['images', 'audio'],
                                  'native_output_names': ['VIDEO'],
                                  'native_input_types': ['IMAGE', 'AUDIO'],
                                  'native_output_types': ['VIDEO'],
                                  'native_input_optional': [False, True],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['VIDEO'],
                              'output_types': ['VIDEO'],
                              'keep_defaults': ['fps']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'savevideo': {'id': '56',
               'uid': '56',
               'class_type': 'SaveVideo',
               'native_ports': {'native_input_names': ['video'],
                                'native_output_names': [],
                                'native_input_types': ['VIDEO'],
                                'native_output_types': [],
                                'native_input_optional': [False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'keep_defaults': ['codec', 'filename_prefix', 'format']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}}}

READY_METADATA = ReadyMetadata.build(
    capability='video',
    template_id='wan_i2v',
    inputs=PUBLIC_INPUT_METADATA,
    requirements={'models': ['clip_vision_h.safetensors', 'umt5_xxl_fp8_e4m3fn_scaled.safetensors', 'wan2.1_i2v_480p_14B_fp16.safetensors', 'wan_2.1_vae.safetensors']},
    provenance={'source_path': 'ready_templates/sources/official/video/wan_i2v.json', 'source_id': 'wan_i2v', 'source_type': 'api', 'source_workflow_path': 'ready_templates/sources/official/video/wan_i2v.json', 'source_ref': 'ready_templates/sources/official/video/wan_i2v.json', 'source_kind': 'raw_json', 'indexed_id': None, 'workflow_source_id': 'wan_i2v', 'workflow_source_type': 'api', 'raw_workflow_shape': 'ui', 'source_hash': 'sha256:e455b28ec1eb5c2312ec4bb65dd2e2e69e9193ee766bdfc251a9c001a15edee4', 'workflow_shape': {'nodes': 15, 'runtime_nodes': 14, 'helper_nodes': 1, 'edges': 18, 'inputs': 4, 'outputs': 1}, 'output_mode': 'scratchpad'},
)

def build() -> VibeWorkflow:
    """Build the workflow (auto-generated)."""
    wf = new_workflow(READY_METADATA, source_path=__file__, canonical_custody=CANONICAL_CUSTODY)

    # Loaders
    unetloader = UNETLoader(unet_name=UNET_NAME, weight_dtype='default')
    cliploader = CLIPLoader(clip_name=CLIP_NAME, type='wan', device='default')
    vaeloader = VAELoader(vae_name=VAE_NAME)
    clipvisionloader = CLIPVisionLoader(clip_name=CLIP_NAME_2)

    # Inputs
    loadimage = LoadImage(image='image_to_video_wan_start_image.png')
    markdownnote = raw_call('MarkdownNote')

    # Conditioning
    cliptextencode = CLIPTextEncode(text=DEFAULT_PROMPT, clip=cliploader.out('CLIP'))

    cliptextencode_2 = CLIPTextEncode(
        text=DEFAULT_PROMPT_2,
        clip=cliploader.out('CLIP'),
    )

    clipvisionencode = CLIPVisionEncode(
        crop='none',
        clip_vision=clipvisionloader.out('CLIP_VISION'),
        image=loadimage.out('IMAGE'),
    )

    modelsamplingsd3 = ModelSamplingSD3(shift=8, model=unetloader.out('MODEL'))

    wanimagetovideo = WanImageToVideo(
        width=512,
        height=512,
        length=DEFAULT_FRAMES,
        batch_size=1,
        clip_vision_output=clipvisionencode.out('CLIP_VISION_OUTPUT'),
        negative=cliptextencode_2.out('CONDITIONING'),
        positive=cliptextencode.out('CONDITIONING'),
        start_image=loadimage.out('IMAGE'),
        vae=vaeloader.out('VAE'),
    )

    # Sampling
    ksampler = KSampler(
        seed=DEFAULT_SEED,
        steps=20,
        cfg=GUIDE_STRENGTH,
        sampler_name='uni_pc',
        scheduler='simple',
        denoise=1,
        control_after_generate='randomize',
        latent_image=wanimagetovideo.out('latent'),
        model=modelsamplingsd3.out('MODEL'),
        negative=wanimagetovideo.out('negative'),
        positive=wanimagetovideo.out('positive'),
    )

    # Decode
    vaedecode = VAEDecode(samples=ksampler.out('LATENT'), vae=vaeloader.out('VAE'))
    createvideo = CreateVideo(fps=DEFAULT_FPS, images=vaedecode.out('IMAGE'))

    # Outputs
    savevideo = SaveVideo(
        filename_prefix='video/ComfyUI',
        format='auto',
        codec='auto',
        video=createvideo.out('VIDEO'),
    )

    wf = wf.finalize(PUBLIC_INPUT_METADATA, canonical_outputs=[{'node': savevideo, 'output_type': 'SaveVideo', 'name': None, 'artifact_kind': None, 'mime_type': None, 'filename_prefix': None, 'expected_cardinality': None}], canonical_requirements={'models': ['clip_vision_h.safetensors', 'umt5_xxl_fp8_e4m3fn_scaled.safetensors', 'wan2.1_i2v_480p_14B_fp16.safetensors', 'wan_2.1_vae.safetensors'], 'custom_nodes': [], 'missing_models': [], 'missing_nodes': [], 'unsupported': []}, canonical_custody=CANONICAL_CUSTODY, canonical_bindings={'unetloader': unetloader, 'cliploader': cliploader, 'vaeloader': vaeloader, 'clipvisionloader': clipvisionloader, 'loadimage': loadimage, 'markdownnote': markdownnote, 'cliptextencode': cliptextencode, 'cliptextencode_2': cliptextencode_2, 'clipvisionencode': clipvisionencode, 'modelsamplingsd3': modelsamplingsd3, 'wanimagetovideo': wanimagetovideo, 'ksampler': ksampler, 'vaedecode': vaedecode, 'createvideo': createvideo, 'savevideo': savevideo})
    wf.strict_types = False
    return wf
