# vibecomfy: generated
# For hand-editing, run: python -m vibecomfy.cli copy-to-recipe <id>
# vibecomfy: surface=canonical
"""Auto-generated ready_template — use python -m vibecomfy.cli copy-to-recipe <id> for hand-editing."""
from __future__ import annotations

from vibecomfy.templates import InputSpec, ReadyMetadata, new_workflow, node as raw_call, ref
from vibecomfy.workflow import VibeWorkflow
from vibecomfy.nodes.core import CFGGuider, CLIPTextEncode, CheckpointLoaderSimple, CreateVideo, EmptyLTXVLatentVideo, GetImageSize, GetVideoComponents, KSamplerSelect, LTXAVTextEncoderLoader, LTXVConditioning, LTXVCropGuides, LoadVideo, ManualSigmas, RandomNoise, ResizeImageMaskNode, SamplerCustomAdvanced, SaveVideo, SimpleMath_2, VAEDecodeTiled
from vibecomfy.nodes.ltxvideo import GemmaAPITextEncode, LTXAddVideoICLoRAGuide, LTXICLoRALoaderModelOnly, LTXVHDRDecodePostprocess


CKPT_NAME = 'ltx-2.3-22b-dev.safetensors'
DEFAULT_FPS = 30
DEFAULT_PROMPT = 'pc game, console game, video game, ugly, still, static, slow'
DEFAULT_PROMPT_2 = 'pc game, console game, video game, cartoon, childish, ugly'
DEFAULT_SEED = 42
GUIDE_STRENGTH = 1
GUIDE_STRENGTH_2 = 0.5
LORA_NAME = 'ltxv/ltx2/ltx-2.3-22b-ic-lora-hdr-0.9.safetensors'
LORA_NAME_2 = 'ltxv/ltx2/ltx-2.3-22b-distilled-lora-384-1.1.safetensors'
TEXT_ENCODER_NAME = 'comfy_gemma_3_12B_it.safetensors'


PUBLIC_INPUT_METADATA = {
    'seed': InputSpec(node=ref('randomnoise'), field='noise_seed', default=None, infer_type=False),
    'model': InputSpec(node=ref('ltxavtextencoderloader'), field='ckpt_name', default=None, infer_type=False),
    'prompt': InputSpec(node=ref('cliptextencode'), field='text', default=None, infer_type=False),
}

CANONICAL_CUSTODY = {'checkpointloadersimple': {'id': '3940',
                            'uid': '3940',
                            'class_type': 'CheckpointLoaderSimple',
                            'native_ports': {'native_input_names': ['ckpt_name'],
                                             'native_output_names': ['MODEL', 'CLIP', 'VAE'],
                                             'native_input_types': ['COMBO'],
                                             'native_output_types': ['MODEL', 'CLIP', 'VAE'],
                                             'native_input_optional': [False],
                                             'native_input_asset_kinds': None,
                                             'native_output_slots': None},
                            'metadata': {'schema_source': {'provider': 'object_info_index',
                                                           'path': None,
                                                           'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                           'server_url': None,
                                                           'package': 'comfy_core',
                                                           'version': None,
                                                           'hash': None,
                                                           'confidence': 0.7},
                                         'provenance': 'untrusted_source',
                                         'output_names': ['MODEL', 'CLIP', 'VAE'],
                                         'output_types': ['MODEL', 'CLIP', 'VAE'],
                                         'keep_defaults': ['ckpt_name']},
                            'widget_channels': {},
                            'none_input_fields': [],
                            'none_widget_fields': [],
                            'output_slot_names': {}},
 'ksamplerselect': {'id': '4831',
                    'uid': '4831',
                    'class_type': 'KSamplerSelect',
                    'native_ports': {'native_input_names': ['sampler_name'],
                                     'native_output_names': ['SAMPLER'],
                                     'native_input_types': ['COMBO'],
                                     'native_output_types': ['SAMPLER'],
                                     'native_input_optional': [False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['SAMPLER'],
                                 'output_types': ['SAMPLER'],
                                 'keep_defaults': ['sampler_name']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'randomnoise': {'id': '4832',
                 'uid': '4832',
                 'class_type': 'RandomNoise',
                 'native_ports': {'native_input_names': ['noise_seed'],
                                  'native_output_names': ['NOISE'],
                                  'native_input_types': ['INT'],
                                  'native_output_types': ['NOISE'],
                                  'native_input_optional': [False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['NOISE'],
                              'output_types': ['NOISE'],
                              'keep_defaults': ['control_after_generate', 'noise_seed']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'gemmaapitextencode': {'id': '5020',
                        'uid': '5020',
                        'class_type': 'GemmaAPITextEncode',
                        'native_ports': {'native_input_names': ['api_key',
                                                                'prompt',
                                                                'enhance_prompt',
                                                                'ckpt_name'],
                                         'native_output_names': ['conditioning'],
                                         'native_input_types': ['STRING', 'STRING', 'BOOLEAN', 'COMBO'],
                                         'native_output_types': ['CONDITIONING'],
                                         'native_input_optional': [False, False, False, False],
                                         'native_input_asset_kinds': None,
                                         'native_output_slots': None},
                        'metadata': {'schema_source': {'provider': 'object_info_index',
                                                       'path': None,
                                                       'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/ComfyUI-LTXVideo@runpod-snapshot.json',
                                                       'server_url': None,
                                                       'package': 'ComfyUI-LTXVideo',
                                                       'version': None,
                                                       'hash': None,
                                                       'confidence': 0.7},
                                     'provenance': 'untrusted_source',
                                     'output_names': ['conditioning'],
                                     'output_types': ['CONDITIONING'],
                                     'keep_defaults': ['ckpt_name', 'enhance_prompt', 'prompt']},
                        'widget_channels': {},
                        'none_input_fields': [],
                        'none_widget_fields': [],
                        'output_slot_names': {}},
 'gemmaapitextencode_2': {'id': '5021',
                          'uid': '5021',
                          'class_type': 'GemmaAPITextEncode',
                          'native_ports': {'native_input_names': ['api_key',
                                                                  'prompt',
                                                                  'enhance_prompt',
                                                                  'ckpt_name'],
                                           'native_output_names': ['conditioning'],
                                           'native_input_types': ['STRING', 'STRING', 'BOOLEAN', 'COMBO'],
                                           'native_output_types': ['CONDITIONING'],
                                           'native_input_optional': [False, False, False, False],
                                           'native_input_asset_kinds': None,
                                           'native_output_slots': None},
                          'metadata': {'schema_source': {'provider': 'object_info_index',
                                                         'path': None,
                                                         'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/ComfyUI-LTXVideo@runpod-snapshot.json',
                                                         'server_url': None,
                                                         'package': 'ComfyUI-LTXVideo',
                                                         'version': None,
                                                         'hash': None,
                                                         'confidence': 0.7},
                                       'provenance': 'untrusted_source',
                                       'output_names': ['conditioning'],
                                       'output_types': ['CONDITIONING'],
                                       'keep_defaults': ['ckpt_name', 'enhance_prompt', 'prompt']},
                          'widget_channels': {},
                          'none_input_fields': [],
                          'none_widget_fields': [],
                          'output_slot_names': {}},
 'ltxavtextencoderloader': {'id': '5023',
                            'uid': '5023',
                            'class_type': 'LTXAVTextEncoderLoader',
                            'native_ports': {'native_input_names': ['text_encoder', 'ckpt_name', 'device'],
                                             'native_output_names': ['CLIP'],
                                             'native_input_types': ['COMBO', 'COMBO', 'COMBO'],
                                             'native_output_types': ['CLIP'],
                                             'native_input_optional': [False, False, False],
                                             'native_input_asset_kinds': None,
                                             'native_output_slots': None},
                            'metadata': {'schema_source': {'provider': 'object_info_index',
                                                           'path': None,
                                                           'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                           'server_url': None,
                                                           'package': 'comfy_core',
                                                           'version': None,
                                                           'hash': None,
                                                           'confidence': 0.7},
                                         'provenance': 'untrusted_source',
                                         'output_names': ['CLIP'],
                                         'output_types': ['CLIP'],
                                         'keep_defaults': ['ckpt_name', 'device', 'text_encoder']},
                            'widget_channels': {},
                            'none_input_fields': [],
                            'none_widget_fields': [],
                            'output_slot_names': {}},
 'manualsigmas': {'id': '5025',
                  'uid': '5025',
                  'class_type': 'ManualSigmas',
                  'native_ports': {'native_input_names': ['sigmas'],
                                   'native_output_names': ['SIGMAS'],
                                   'native_input_types': ['STRING'],
                                   'native_output_types': ['SIGMAS'],
                                   'native_input_optional': [False],
                                   'native_input_asset_kinds': None,
                                   'native_output_slots': None},
                  'metadata': {'schema_source': {'provider': 'object_info_index',
                                                 'path': None,
                                                 'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                 'server_url': None,
                                                 'package': 'comfy_core',
                                                 'version': None,
                                                 'hash': None,
                                                 'confidence': 0.7},
                               'provenance': 'untrusted_source',
                               'output_names': ['SIGMAS'],
                               'output_types': ['SIGMAS'],
                               'keep_defaults': ['sigmas']},
                  'widget_channels': {},
                  'none_input_fields': [],
                  'none_widget_fields': [],
                  'output_slot_names': {}},
 'loadvideo': {'id': '5106',
               'uid': '5106',
               'class_type': 'LoadVideo',
               'native_ports': {'native_input_names': ['file', 'upload'],
                                'native_output_names': ['VIDEO'],
                                'native_input_types': ['COMBO', 'IMAGEUPLOAD'],
                                'native_output_types': ['VIDEO'],
                                'native_input_optional': [False, False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'output_names': ['VIDEO'],
                            'output_types': ['VIDEO'],
                            'keep_defaults': ['file', 'upload']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}},
 'note': {'id': '5113',
          'uid': '5113',
          'class_type': 'Note',
          'native_ports': {'native_input_names': [],
                           'native_output_names': [],
                           'native_input_types': [],
                           'native_output_types': [],
                           'native_input_optional': [],
                           'native_input_asset_kinds': None,
                           'native_output_slots': None},
          'metadata': {'schema_source': {'provider': '',
                                         'path': None,
                                         'cache_path': None,
                                         'server_url': None,
                                         'package': None,
                                         'version': None,
                                         'hash': None,
                                         'confidence': 0.0},
                       'provenance': 'untrusted_source',
                       'keep_defaults': ['widget_0']},
          'widget_channels': {'widget_0': 'widget_0'},
          'none_input_fields': [],
          'none_widget_fields': [],
          'output_slot_names': {}},
 'note_2': {'id': '5117',
            'uid': '5117',
            'class_type': 'Note',
            'native_ports': {'native_input_names': [],
                             'native_output_names': [],
                             'native_input_types': [],
                             'native_output_types': [],
                             'native_input_optional': [],
                             'native_input_asset_kinds': None,
                             'native_output_slots': None},
            'metadata': {'schema_source': {'provider': '',
                                           'path': None,
                                           'cache_path': None,
                                           'server_url': None,
                                           'package': None,
                                           'version': None,
                                           'hash': None,
                                           'confidence': 0.0},
                         'provenance': 'untrusted_source',
                         'keep_defaults': ['widget_0']},
            'widget_channels': {'widget_0': 'widget_0'},
            'none_input_fields': [],
            'none_widget_fields': [],
            'output_slot_names': {}},
 'note_3': {'id': '5118',
            'uid': '5118',
            'class_type': 'Note',
            'native_ports': {'native_input_names': [],
                             'native_output_names': [],
                             'native_input_types': [],
                             'native_output_types': [],
                             'native_input_optional': [],
                             'native_input_asset_kinds': None,
                             'native_output_slots': None},
            'metadata': {'schema_source': {'provider': '',
                                           'path': None,
                                           'cache_path': None,
                                           'server_url': None,
                                           'package': None,
                                           'version': None,
                                           'hash': None,
                                           'confidence': 0.0},
                         'provenance': 'untrusted_source',
                         'keep_defaults': ['widget_0']},
            'widget_channels': {'widget_0': 'widget_0'},
            'none_input_fields': [],
            'none_widget_fields': [],
            'output_slot_names': {}},
 'note_4': {'id': '5119',
            'uid': '5119',
            'class_type': 'Note',
            'native_ports': {'native_input_names': [],
                             'native_output_names': [],
                             'native_input_types': [],
                             'native_output_types': [],
                             'native_input_optional': [],
                             'native_input_asset_kinds': None,
                             'native_output_slots': None},
            'metadata': {'schema_source': {'provider': '',
                                           'path': None,
                                           'cache_path': None,
                                           'server_url': None,
                                           'package': None,
                                           'version': None,
                                           'hash': None,
                                           'confidence': 0.0},
                         'provenance': 'untrusted_source',
                         'keep_defaults': ['widget_0']},
            'widget_channels': {'widget_0': 'widget_0'},
            'none_input_fields': [],
            'none_widget_fields': [],
            'output_slot_names': {}},
 'note_5': {'id': '5120',
            'uid': '5120',
            'class_type': 'Note',
            'native_ports': {'native_input_names': [],
                             'native_output_names': [],
                             'native_input_types': [],
                             'native_output_types': [],
                             'native_input_optional': [],
                             'native_input_asset_kinds': None,
                             'native_output_slots': None},
            'metadata': {'schema_source': {'provider': '',
                                           'path': None,
                                           'cache_path': None,
                                           'server_url': None,
                                           'package': None,
                                           'version': None,
                                           'hash': None,
                                           'confidence': 0.0},
                         'provenance': 'untrusted_source',
                         'keep_defaults': ['widget_0']},
            'widget_channels': {'widget_0': 'widget_0'},
            'none_input_fields': [],
            'none_widget_fields': [],
            'output_slot_names': {}},
 'note_6': {'id': '5121',
            'uid': '5121',
            'class_type': 'Note',
            'native_ports': {'native_input_names': [],
                             'native_output_names': [],
                             'native_input_types': [],
                             'native_output_types': [],
                             'native_input_optional': [],
                             'native_input_asset_kinds': None,
                             'native_output_slots': None},
            'metadata': {'schema_source': {'provider': '',
                                           'path': None,
                                           'cache_path': None,
                                           'server_url': None,
                                           'package': None,
                                           'version': None,
                                           'hash': None,
                                           'confidence': 0.0},
                         'provenance': 'untrusted_source',
                         'keep_defaults': ['widget_0']},
            'widget_channels': {'widget_0': 'widget_0'},
            'none_input_fields': [],
            'none_widget_fields': [],
            'output_slot_names': {}},
 'cliptextencode': {'id': '2483',
                    'uid': '2483',
                    'class_type': 'CLIPTextEncode',
                    'native_ports': {'native_input_names': ['clip', 'text'],
                                     'native_output_names': ['CONDITIONING'],
                                     'native_input_types': ['CLIP', 'STRING'],
                                     'native_output_types': ['CONDITIONING'],
                                     'native_input_optional': [False, False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['CONDITIONING'],
                                 'output_types': ['CONDITIONING'],
                                 'keep_defaults': ['text']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'cliptextencode_2': {'id': '2612',
                      'uid': '2612',
                      'class_type': 'CLIPTextEncode',
                      'native_ports': {'native_input_names': ['clip', 'text'],
                                       'native_output_names': ['CONDITIONING'],
                                       'native_input_types': ['CLIP', 'STRING'],
                                       'native_output_types': ['CONDITIONING'],
                                       'native_input_optional': [False, False],
                                       'native_input_asset_kinds': None,
                                       'native_output_slots': None},
                      'metadata': {'schema_source': {'provider': 'object_info_index',
                                                     'path': None,
                                                     'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                     'server_url': None,
                                                     'package': 'comfy_core',
                                                     'version': None,
                                                     'hash': None,
                                                     'confidence': 0.7},
                                   'provenance': 'untrusted_source',
                                   'output_names': ['CONDITIONING'],
                                   'output_types': ['CONDITIONING'],
                                   'keep_defaults': ['text']},
                      'widget_channels': {},
                      'none_input_fields': [],
                      'none_widget_fields': [],
                      'output_slot_names': {}},
 'getvideocomponents': {'id': '5105',
                        'uid': '5105',
                        'class_type': 'GetVideoComponents',
                        'native_ports': {'native_input_names': ['video'],
                                         'native_output_names': ['images', 'audio', 'fps'],
                                         'native_input_types': ['VIDEO'],
                                         'native_output_types': ['IMAGE', 'AUDIO', 'FLOAT'],
                                         'native_input_optional': [False],
                                         'native_input_asset_kinds': None,
                                         'native_output_slots': None},
                        'metadata': {'schema_source': {'provider': 'object_info_index',
                                                       'path': None,
                                                       'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                       'server_url': None,
                                                       'package': 'comfy_core',
                                                       'version': None,
                                                       'hash': None,
                                                       'confidence': 0.7},
                                     'provenance': 'untrusted_source',
                                     'output_names': ['images', 'audio', 'fps'],
                                     'output_types': ['IMAGE', 'AUDIO', 'FLOAT']},
                        'widget_channels': {},
                        'none_input_fields': [],
                        'none_widget_fields': [],
                        'output_slot_names': {}},
 'ltxicloraloadermodelonly_2': {'id': '5125',
                                'uid': '5125',
                                'class_type': 'LTXICLoRALoaderModelOnly',
                                'native_ports': {'native_input_names': ['model',
                                                                        'lora_name',
                                                                        'strength_model'],
                                                 'native_output_names': ['model', 'latent_downscale_factor'],
                                                 'native_input_types': ['MODEL', 'COMBO', 'FLOAT'],
                                                 'native_output_types': ['MODEL', 'FLOAT'],
                                                 'native_input_optional': [False, False, False],
                                                 'native_input_asset_kinds': None,
                                                 'native_output_slots': None},
                                'metadata': {'schema_source': {'provider': 'object_info_index',
                                                               'path': None,
                                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/ComfyUI-LTXVideo@runpod-snapshot.json',
                                                               'server_url': None,
                                                               'package': 'ComfyUI-LTXVideo',
                                                               'version': None,
                                                               'hash': None,
                                                               'confidence': 0.7},
                                             'provenance': 'untrusted_source',
                                             'output_names': ['model', 'latent_downscale_factor'],
                                             'output_types': ['MODEL', 'FLOAT'],
                                             'keep_defaults': ['lora_name', 'strength_model']},
                                'widget_channels': {},
                                'none_input_fields': [],
                                'none_widget_fields': [],
                                'output_slot_names': {}},
 'ltxvconditioning': {'id': '1241',
                      'uid': '1241',
                      'class_type': 'LTXVConditioning',
                      'native_ports': {'native_input_names': ['positive', 'negative', 'frame_rate'],
                                       'native_output_names': ['positive', 'negative'],
                                       'native_input_types': ['CONDITIONING', 'CONDITIONING', 'FLOAT'],
                                       'native_output_types': ['CONDITIONING', 'CONDITIONING'],
                                       'native_input_optional': [False, False, False],
                                       'native_input_asset_kinds': None,
                                       'native_output_slots': None},
                      'metadata': {'schema_source': {'provider': 'object_info_index',
                                                     'path': None,
                                                     'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                     'server_url': None,
                                                     'package': 'comfy_core',
                                                     'version': None,
                                                     'hash': None,
                                                     'confidence': 0.7},
                                   'provenance': 'untrusted_source',
                                   'output_names': ['positive', 'negative'],
                                   'output_types': ['CONDITIONING', 'CONDITIONING']},
                      'widget_channels': {},
                      'none_input_fields': [],
                      'none_widget_fields': [],
                      'output_slot_names': {}},
 'ltxicloraloadermodelonly': {'id': '5011',
                              'uid': '5011',
                              'class_type': 'LTXICLoRALoaderModelOnly',
                              'native_ports': {'native_input_names': ['model', 'lora_name', 'strength_model'],
                                               'native_output_names': ['model', 'latent_downscale_factor'],
                                               'native_input_types': ['MODEL', 'COMBO', 'FLOAT'],
                                               'native_output_types': ['MODEL', 'FLOAT'],
                                               'native_input_optional': [False, False, False],
                                               'native_input_asset_kinds': None,
                                               'native_output_slots': None},
                              'metadata': {'schema_source': {'provider': 'object_info_index',
                                                             'path': None,
                                                             'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/ComfyUI-LTXVideo@runpod-snapshot.json',
                                                             'server_url': None,
                                                             'package': 'ComfyUI-LTXVideo',
                                                             'version': None,
                                                             'hash': None,
                                                             'confidence': 0.7},
                                           'provenance': 'untrusted_source',
                                           'output_names': ['model', 'latent_downscale_factor'],
                                           'output_types': ['MODEL', 'FLOAT'],
                                           'keep_defaults': ['lora_name', 'strength_model']},
                              'widget_channels': {},
                              'none_input_fields': [],
                              'none_widget_fields': [],
                              'output_slot_names': {}},
 'simplemath_': {'id': '5111',
                 'uid': '5111',
                 'class_type': 'SimpleMath+',
                 'native_ports': {'native_input_names': ['a', 'b', 'c', 'value'],
                                  'native_output_names': ['INT', 'FLOAT'],
                                  'native_input_types': ['*', '*', '*', 'STRING'],
                                  'native_output_types': ['INT', 'FLOAT'],
                                  'native_input_optional': [True, True, True, False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['INT', 'FLOAT'],
                              'output_types': ['INT', 'FLOAT'],
                              'keep_defaults': ['value']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'resizeimagemasknode': {'id': '5112',
                         'uid': '5112',
                         'class_type': 'ResizeImageMaskNode',
                         'native_ports': {'native_input_names': ['input',
                                                                 'resize_type',
                                                                 'resize_type.multiple',
                                                                 'scale_method'],
                                          'native_output_names': ['resized'],
                                          'native_input_types': ['IMAGE,MASK',
                                                                 'COMFY_DYNAMICCOMBO_V3',
                                                                 'INT',
                                                                 'COMBO'],
                                          'native_output_types': ['IMAGE'],
                                          'native_input_optional': [False, False, False, False],
                                          'native_input_asset_kinds': None,
                                          'native_output_slots': None},
                         'metadata': {'schema_source': {'provider': 'object_info_index',
                                                        'path': None,
                                                        'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                        'server_url': None,
                                                        'package': 'comfy_core',
                                                        'version': None,
                                                        'hash': None,
                                                        'confidence': 0.7},
                                      'provenance': 'untrusted_source',
                                      'output_names': ['resized'],
                                      'output_types': ['COMFY_MATCHTYPE_V3'],
                                      'keep_defaults': ['resize_type', 'scale_method', 'unused_widget_1']},
                         'widget_channels': {},
                         'none_input_fields': [],
                         'none_widget_fields': [],
                         'output_slot_names': {}},
 'getimagesize': {'id': '5029',
                  'uid': '5029',
                  'class_type': 'GetImageSize',
                  'native_ports': {'native_input_names': ['image'],
                                   'native_output_names': ['width', 'height', 'batch_size'],
                                   'native_input_types': ['IMAGE'],
                                   'native_output_types': ['INT', 'INT', 'INT'],
                                   'native_input_optional': [False],
                                   'native_input_asset_kinds': None,
                                   'native_output_slots': None},
                  'metadata': {'schema_source': {'provider': 'object_info_index',
                                                 'path': None,
                                                 'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                 'server_url': None,
                                                 'package': 'comfy_core',
                                                 'version': None,
                                                 'hash': None,
                                                 'confidence': 0.7},
                               'provenance': 'untrusted_source',
                               'output_names': ['width', 'height', 'batch_size'],
                               'output_types': ['INT', 'INT', 'INT']},
                  'widget_channels': {},
                  'none_input_fields': [],
                  'none_widget_fields': [],
                  'output_slot_names': {}},
 'emptyltxvlatentvideo': {'id': '3059',
                          'uid': '3059',
                          'class_type': 'EmptyLTXVLatentVideo',
                          'native_ports': {'native_input_names': ['width', 'height', 'length', 'batch_size'],
                                           'native_output_names': ['LATENT'],
                                           'native_input_types': ['INT', 'INT', 'INT', 'INT'],
                                           'native_output_types': ['LATENT'],
                                           'native_input_optional': [False, False, False, False],
                                           'native_input_asset_kinds': None,
                                           'native_output_slots': None},
                          'metadata': {'schema_source': {'provider': 'object_info_index',
                                                         'path': None,
                                                         'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                         'server_url': None,
                                                         'package': 'comfy_core',
                                                         'version': None,
                                                         'hash': None,
                                                         'confidence': 0.7},
                                       'provenance': 'untrusted_source',
                                       'output_names': ['LATENT'],
                                       'output_types': ['LATENT'],
                                       'keep_defaults': ['batch_size']},
                          'widget_channels': {},
                          'none_input_fields': [],
                          'none_widget_fields': [],
                          'output_slot_names': {}},
 'ltxaddvideoicloraguide': {'id': '5012',
                            'uid': '5012',
                            'class_type': 'LTXAddVideoICLoRAGuide',
                            'native_ports': {'native_input_names': ['positive',
                                                                    'negative',
                                                                    'vae',
                                                                    'latent',
                                                                    'image',
                                                                    'frame_idx',
                                                                    'strength',
                                                                    'latent_downscale_factor',
                                                                    'crop',
                                                                    'use_tiled_encode',
                                                                    'tile_size',
                                                                    'tile_overlap'],
                                             'native_output_names': ['positive', 'negative', 'latent'],
                                             'native_input_types': ['CONDITIONING',
                                                                    'CONDITIONING',
                                                                    'VAE',
                                                                    'LATENT',
                                                                    'IMAGE',
                                                                    'INT',
                                                                    'FLOAT',
                                                                    'FLOAT',
                                                                    'COMBO',
                                                                    'BOOLEAN',
                                                                    'INT',
                                                                    'INT'],
                                             'native_output_types': ['CONDITIONING',
                                                                     'CONDITIONING',
                                                                     'LATENT'],
                                             'native_input_optional': [False,
                                                                       False,
                                                                       False,
                                                                       False,
                                                                       False,
                                                                       False,
                                                                       False,
                                                                       False,
                                                                       False,
                                                                       False,
                                                                       False,
                                                                       False],
                                             'native_input_asset_kinds': None,
                                             'native_output_slots': None},
                            'metadata': {'schema_source': {'provider': 'object_info_index',
                                                           'path': None,
                                                           'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/ComfyUI-LTXVideo@runpod-snapshot.json',
                                                           'server_url': None,
                                                           'package': 'ComfyUI-LTXVideo',
                                                           'version': None,
                                                           'hash': None,
                                                           'confidence': 0.7},
                                         'provenance': 'untrusted_source',
                                         'output_names': ['positive', 'negative', 'latent'],
                                         'output_types': ['CONDITIONING', 'CONDITIONING', 'LATENT'],
                                         'keep_defaults': ['crop',
                                                           'frame_idx',
                                                           'latent_downscale_factor',
                                                           'strength',
                                                           'tile_overlap',
                                                           'tile_size',
                                                           'use_tiled_encode']},
                            'widget_channels': {},
                            'none_input_fields': [],
                            'none_widget_fields': [],
                            'output_slot_names': {}},
 'cfgguider': {'id': '4828',
               'uid': '4828',
               'class_type': 'CFGGuider',
               'native_ports': {'native_input_names': ['model', 'positive', 'negative', 'cfg'],
                                'native_output_names': ['GUIDER'],
                                'native_input_types': ['MODEL', 'CONDITIONING', 'CONDITIONING', 'FLOAT'],
                                'native_output_types': ['GUIDER'],
                                'native_input_optional': [False, False, False, False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'output_names': ['GUIDER'],
                            'output_types': ['GUIDER'],
                            'keep_defaults': ['cfg']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}},
 'samplercustomadvanced': {'id': '4829',
                           'uid': '4829',
                           'class_type': 'SamplerCustomAdvanced',
                           'native_ports': {'native_input_names': ['noise',
                                                                   'guider',
                                                                   'sampler',
                                                                   'sigmas',
                                                                   'latent_image'],
                                            'native_output_names': ['output', 'denoised_output'],
                                            'native_input_types': ['NOISE',
                                                                   'GUIDER',
                                                                   'SAMPLER',
                                                                   'SIGMAS',
                                                                   'LATENT'],
                                            'native_output_types': ['LATENT', 'LATENT'],
                                            'native_input_optional': [False, False, False, False, False],
                                            'native_input_asset_kinds': None,
                                            'native_output_slots': None},
                           'metadata': {'schema_source': {'provider': 'object_info_index',
                                                          'path': None,
                                                          'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                          'server_url': None,
                                                          'package': 'comfy_core',
                                                          'version': None,
                                                          'hash': None,
                                                          'confidence': 0.7},
                                        'provenance': 'untrusted_source',
                                        'output_names': ['output', 'denoised_output'],
                                        'output_types': ['LATENT', 'LATENT']},
                           'widget_channels': {},
                           'none_input_fields': [],
                           'none_widget_fields': [],
                           'output_slot_names': {}},
 'ltxvcropguides': {'id': '5013',
                    'uid': '5013',
                    'class_type': 'LTXVCropGuides',
                    'native_ports': {'native_input_names': ['positive', 'negative', 'latent'],
                                     'native_output_names': ['positive', 'negative', 'latent'],
                                     'native_input_types': ['CONDITIONING', 'CONDITIONING', 'LATENT'],
                                     'native_output_types': ['CONDITIONING', 'CONDITIONING', 'LATENT'],
                                     'native_input_optional': [False, False, False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['positive', 'negative', 'latent'],
                                 'output_types': ['CONDITIONING', 'CONDITIONING', 'LATENT']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'vaedecodetiled': {'id': '4851',
                    'uid': '4851',
                    'class_type': 'VAEDecodeTiled',
                    'native_ports': {'native_input_names': ['samples',
                                                            'vae',
                                                            'tile_size',
                                                            'overlap',
                                                            'temporal_size',
                                                            'temporal_overlap'],
                                     'native_output_names': ['IMAGE'],
                                     'native_input_types': ['LATENT', 'VAE', 'INT', 'INT', 'INT', 'INT'],
                                     'native_output_types': ['IMAGE'],
                                     'native_input_optional': [False, False, False, False, False, False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['IMAGE'],
                                 'output_types': ['IMAGE'],
                                 'keep_defaults': ['overlap',
                                                   'temporal_overlap',
                                                   'temporal_size',
                                                   'tile_size']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'ltxvhdrdecodepostprocess': {'id': '5114',
                              'uid': '5114',
                              'class_type': 'LTXVHDRDecodePostprocess',
                              'native_ports': {'native_input_names': ['image',
                                                                      'exposure',
                                                                      'save_exr',
                                                                      'output_dir',
                                                                      'filename_prefix',
                                                                      'half_precision'],
                                               'native_output_names': ['tonemapped', 'hdr_linear'],
                                               'native_input_types': ['IMAGE',
                                                                      'FLOAT',
                                                                      'BOOLEAN',
                                                                      'STRING',
                                                                      'STRING',
                                                                      'BOOLEAN'],
                                               'native_output_types': ['IMAGE', 'IMAGE'],
                                               'native_input_optional': [False, True, True, True, True, True],
                                               'native_input_asset_kinds': None,
                                               'native_output_slots': None},
                              'metadata': {'schema_source': {'provider': 'object_info_index',
                                                             'path': None,
                                                             'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/ComfyUI-LTXVideo@runpod-snapshot.json',
                                                             'server_url': None,
                                                             'package': 'ComfyUI-LTXVideo',
                                                             'version': None,
                                                             'hash': None,
                                                             'confidence': 0.7},
                                           'provenance': 'untrusted_source',
                                           'output_names': ['tonemapped', 'hdr_linear'],
                                           'output_types': ['IMAGE', 'IMAGE'],
                                           'keep_defaults': ['exposure',
                                                             'filename_prefix',
                                                             'half_precision',
                                                             'output_dir',
                                                             'save_exr']},
                              'widget_channels': {},
                              'none_input_fields': [],
                              'none_widget_fields': [],
                              'output_slot_names': {}},
 'createvideo': {'id': '5108',
                 'uid': '5108',
                 'class_type': 'CreateVideo',
                 'native_ports': {'native_input_names': ['images', 'audio', 'fps'],
                                  'native_output_names': ['VIDEO'],
                                  'native_input_types': ['IMAGE', 'AUDIO', 'FLOAT'],
                                  'native_output_types': ['VIDEO'],
                                  'native_input_optional': [False, True, False],
                                  'native_input_asset_kinds': None,
                                  'native_output_slots': None},
                 'metadata': {'schema_source': {'provider': 'object_info_index',
                                                'path': None,
                                                'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                'server_url': None,
                                                'package': 'comfy_core',
                                                'version': None,
                                                'hash': None,
                                                'confidence': 0.7},
                              'provenance': 'untrusted_source',
                              'output_names': ['VIDEO'],
                              'output_types': ['VIDEO'],
                              'keep_defaults': ['fps']},
                 'widget_channels': {},
                 'none_input_fields': [],
                 'none_widget_fields': [],
                 'output_slot_names': {}},
 'savevideo': {'id': '5109',
               'uid': '5109',
               'class_type': 'SaveVideo',
               'native_ports': {'native_input_names': ['video', 'filename_prefix', 'format', 'codec'],
                                'native_output_names': [],
                                'native_input_types': ['VIDEO', 'STRING', 'COMBO', 'COMBO'],
                                'native_output_types': [],
                                'native_input_optional': [False, False, False, False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'keep_defaults': ['codec', 'filename_prefix', 'format']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}}}
HELPER_CUSTODY = [{'id': '5022',
  'uid': '5022',
  'class_type': 'PrimitiveString',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': ['value'],
                   'native_output_names': ['STRING'],
                   'native_input_types': ['STRING'],
                   'native_output_types': ['STRING'],
                   'native_input_optional': [False],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}}]

READY_METADATA = ReadyMetadata.build(
    capability='video',
    template_id='LTX-2.3_ICLoRA_HDR_Distilled',
    inputs=PUBLIC_INPUT_METADATA,
    requirements={'models': ['ltx-2.3-22b-dev.safetensors', 'ltxv/ltx2/ltx-2.3-22b-distilled-lora-384-1.1.safetensors', 'ltxv/ltx2/ltx-2.3-22b-ic-lora-hdr-0.9.safetensors']},
    custom_node_packs={'ComfyUI-LTXVideo': {'commit': '229437c6b65796d6a7a63ae34be2bd5ba31fa543', 'url': 'https://github.com/Lightricks/ComfyUI-LTXVideo.git', 'class_schema_sha256': '82e0b1f31509a969cf441c45e2517d0cd93f31b5390cc16f4a0ffa244421f39e', 'classes_used': ['EmptyLTXVLatentVideo', 'LTXAVTextEncoderLoader', 'LTXVConditioning', 'LTXVCropGuides'], 'pip_packages': [], 'status': 'discovered'}},
    provenance={'source_path': 'ready_templates/sources/custom_nodes/ltxvideo/lightricks_2_3/LTX-2.3_ICLoRA_HDR_Distilled.json', 'source_id': 'LTX-2.3_ICLoRA_HDR_Distilled', 'source_type': 'api', 'source_workflow_path': 'ready_templates/sources/custom_nodes/ltxvideo/lightricks_2_3/LTX-2.3_ICLoRA_HDR_Distilled.json', 'source_ref': 'ready_templates/sources/custom_nodes/ltxvideo/lightricks_2_3/LTX-2.3_ICLoRA_HDR_Distilled.json', 'source_kind': 'raw_json', 'indexed_id': None, 'workflow_source_id': 'LTX-2.3_ICLoRA_HDR_Distilled', 'workflow_source_type': 'api', 'raw_workflow_shape': 'ui', 'source_hash': 'sha256:63dfbf9819ccbc4189964b6adccec84199e9763621c40ba0dd0f2eb0e462fd25', 'workflow_shape': {'nodes': 33, 'runtime_nodes': 27, 'helper_nodes': 6, 'edges': 39, 'inputs': 3, 'outputs': 1}, 'output_mode': 'scratchpad'},
)

def build() -> VibeWorkflow:
    """Build the workflow (auto-generated)."""
    wf = new_workflow(READY_METADATA, source_path=__file__, canonical_custody=CANONICAL_CUSTODY)

    # Loaders
    checkpointloadersimple = CheckpointLoaderSimple(ckpt_name=CKPT_NAME)

    # Sampling
    ksamplerselect = KSamplerSelect(sampler_name='euler_ancestral')
    randomnoise = RandomNoise(noise_seed=DEFAULT_SEED, control_after_generate='fixed')

    gemmaapitextencode = GemmaAPITextEncode(
        ckpt_name=CKPT_NAME,
        enhance_prompt=False,
        prompt=DEFAULT_PROMPT_2,
        _mode=4,
    )

    gemmaapitextencode_2 = GemmaAPITextEncode(
        ckpt_name=CKPT_NAME,
        enhance_prompt=CKPT_NAME,
        prompt='',
        _mode=4,
    )

    ltxavtextencoderloader = LTXAVTextEncoderLoader(
        text_encoder=TEXT_ENCODER_NAME,
        ckpt_name=CKPT_NAME,
        device='default',
    )

    manualsigmas = ManualSigmas(
        sigmas='1.0, 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0',
    )

    loadvideo = LoadVideo(file='hdr_input_video (1).mp4', upload='image')

    note = raw_call('Note',
        widget_0='The flow will generate the closest 8XF-1 in the input video length\n\nExpected runinng times on H1 machine\n\nFull HD 1080*1920\n 161 frames 100 secs\n 241 frames 152 secs\n \n\n\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0',
    )

    note_2 = raw_call('Note',
        widget_0='Set OPENCV_IO_ENABLE_OPENEXR=1 in your shell before launching ComfyUI, otherwise save_exr will fail',
    )

    note_3 = raw_call('Note',
        widget_0="EXR output is best viewed in DJV — standard image viewers won't display linear HDR correctly.",
    )

    note_4 = raw_call('Note',
        widget_0='equires ltx-2.3-22b-ic-lora-hdr-0.9.safetensors from Lightricks/LTX-2.3-22b-IC-LoRA-HDR. Place in models/loras/',
    )

    note_5 = raw_call('Note',
        widget_0='Exposure adjusts the SDR preview only (in stops, ±10 EV). Does not affect hdr_linear or the saved EXR.',
    )

    note_6 = raw_call('Note', widget_0='in case of OOM use tile_size of 768\ntemporal size 16')

    # Conditioning
    cliptextencode = CLIPTextEncode(
        text='HDR footage',
        clip=ltxavtextencoderloader.out('CLIP'),
    )

    cliptextencode_2 = CLIPTextEncode(
        text=DEFAULT_PROMPT,
        clip=ltxavtextencoderloader.out('CLIP'),
    )

    getvideocomponents = GetVideoComponents(video=loadvideo.out('VIDEO'))

    ltxicloraloadermodelonly_2 = LTXICLoRALoaderModelOnly(
        lora_name=LORA_NAME_2,
        strength_model=GUIDE_STRENGTH_2,
        model=checkpointloadersimple.out('MODEL'),
    )

    ltxvconditioning = LTXVConditioning(
        frame_rate=getvideocomponents.out('fps'),
        negative=cliptextencode_2.out('CONDITIONING'),
        positive=cliptextencode.out('CONDITIONING'),
    )

    ltxicloraloadermodelonly = LTXICLoRALoaderModelOnly(
        lora_name=LORA_NAME,
        strength_model=GUIDE_STRENGTH,
        model=ltxicloraloadermodelonly_2.out('model'),
    )

    simplemath_ = SimpleMath_2(
        value='a*32',
        a=ltxicloraloadermodelonly.out('latent_downscale_factor'),
    )

    resizeimagemasknode = ResizeImageMaskNode(
        resize_type='scale to multiple',
        scale_method='lanczos',
        input=getvideocomponents.out('images'),
        **{'resize_type.multiple': simplemath_.out('INT')},
    )

    getimagesize = GetImageSize(image=resizeimagemasknode.out('resized'))

    emptyltxvlatentvideo = EmptyLTXVLatentVideo(
        batch_size=1,
        width=getimagesize.out('width'),
        height=getimagesize.out('height'),
        length=getimagesize.out('batch_size'),
    )

    ltxaddvideoicloraguide = LTXAddVideoICLoRAGuide(
        frame_idx=0,
        strength=1,
        crop='disabled',
        use_tiled_encode=False,
        tile_size=256,
        tile_overlap=64,
        latent_downscale_factor=1,
        image=resizeimagemasknode.out('resized'),
        latent=emptyltxvlatentvideo.out('LATENT'),
        negative=ltxvconditioning.out('negative'),
        positive=ltxvconditioning.out('positive'),
        vae=checkpointloadersimple.out('VAE'),
    )

    cfgguider = CFGGuider(
        cfg=GUIDE_STRENGTH,
        model=ltxicloraloadermodelonly.out('model'),
        negative=ltxaddvideoicloraguide.out('negative'),
        positive=ltxaddvideoicloraguide.out('positive'),
    )

    samplercustomadvanced = SamplerCustomAdvanced(
        guider=cfgguider.out('GUIDER'),
        latent_image=ltxaddvideoicloraguide.out('latent'),
        noise=randomnoise.out('NOISE'),
        sampler=ksamplerselect.out('SAMPLER'),
        sigmas=manualsigmas.out('SIGMAS'),
    )

    ltxvcropguides = LTXVCropGuides(
        latent=samplercustomadvanced.out('output'),
        negative=ltxaddvideoicloraguide.out('negative'),
        positive=ltxaddvideoicloraguide.out('positive'),
    )

    # Decode
    vaedecodetiled = VAEDecodeTiled(
        tile_size=768,
        overlap=256,
        temporal_size=8,
        temporal_overlap=4,
        samples=ltxvcropguides.out('latent'),
        vae=checkpointloadersimple.out('VAE'),
    )

    ltxvhdrdecodepostprocess = LTXVHDRDecodePostprocess(
        exposure=7.1,
        filename_prefix='frame',
        half_precision=True,
        output_dir='output/hdr_exr3',
        save_exr=True,
        image=vaedecodetiled.out('IMAGE'),
    )

    createvideo = CreateVideo(
        fps=DEFAULT_FPS,
        audio=getvideocomponents.out('audio'),
        images=ltxvhdrdecodepostprocess.out('hdr_linear'),
    )

    # Outputs
    savevideo = SaveVideo(
        filename_prefix='output',
        format='auto',
        codec='auto',
        video=createvideo.out('VIDEO'),
    )

    wf = wf.finalize(PUBLIC_INPUT_METADATA, canonical_outputs=[{'node': savevideo, 'output_type': 'SaveVideo', 'name': None, 'artifact_kind': None, 'mime_type': None, 'filename_prefix': None, 'expected_cardinality': None}], canonical_requirements={'models': ['ltx-2.3-22b-dev.safetensors', 'ltxv/ltx2/ltx-2.3-22b-distilled-lora-384-1.1.safetensors', 'ltxv/ltx2/ltx-2.3-22b-ic-lora-hdr-0.9.safetensors'], 'custom_nodes': [], 'missing_models': [], 'missing_nodes': ['Note'], 'unsupported': []}, canonical_custody=CANONICAL_CUSTODY, canonical_bindings={'checkpointloadersimple': checkpointloadersimple, 'ksamplerselect': ksamplerselect, 'randomnoise': randomnoise, 'gemmaapitextencode': gemmaapitextencode, 'gemmaapitextencode_2': gemmaapitextencode_2, 'ltxavtextencoderloader': ltxavtextencoderloader, 'manualsigmas': manualsigmas, 'loadvideo': loadvideo, 'note': note, 'note_2': note_2, 'note_3': note_3, 'note_4': note_4, 'note_5': note_5, 'note_6': note_6, 'cliptextencode': cliptextencode, 'cliptextencode_2': cliptextencode_2, 'getvideocomponents': getvideocomponents, 'ltxicloraloadermodelonly_2': ltxicloraloadermodelonly_2, 'ltxvconditioning': ltxvconditioning, 'ltxicloraloadermodelonly': ltxicloraloadermodelonly, 'simplemath_': simplemath_, 'resizeimagemasknode': resizeimagemasknode, 'getimagesize': getimagesize, 'emptyltxvlatentvideo': emptyltxvlatentvideo, 'ltxaddvideoicloraguide': ltxaddvideoicloraguide, 'cfgguider': cfgguider, 'samplercustomadvanced': samplercustomadvanced, 'ltxvcropguides': ltxvcropguides, 'vaedecodetiled': vaedecodetiled, 'ltxvhdrdecodepostprocess': ltxvhdrdecodepostprocess, 'createvideo': createvideo, 'savevideo': savevideo}, canonical_helpers=HELPER_CUSTODY)
    wf.strict_types = False
    return wf
