# vibecomfy: generated
# For hand-editing, run: python -m vibecomfy.cli copy-to-recipe <id>
# vibecomfy: surface=canonical
"""Auto-generated ready_template — use python -m vibecomfy.cli copy-to-recipe <id> for hand-editing."""
from __future__ import annotations

from vibecomfy.templates import InputSpec, ReadyMetadata, new_workflow, ref
from vibecomfy.workflow import VibeWorkflow
from vibecomfy.nodes.core import ConditioningZeroOut, DualCLIPLoader, EmptyAceStep1_5LatentAudio, KSampler, ModelSamplingAuraFlow, SaveAudioMP3, TextEncodeAceStepAudio1_5, UNETLoader, VAEDecodeAudio, VAELoader


CLIP_NAME = 'qwen_0.6b_ace15.safetensors'
CLIP_NAME_2 = 'qwen_4b_ace15.safetensors'
DEFAULT_SEED = 561594583201063
FIXED = 'fixed'
GUIDE_STRENGTH = 1
UNET_NAME = 'acestep_v1.5_turbo.safetensors'
VAE_NAME = 'ace_1.5_vae.safetensors'


PUBLIC_INPUT_METADATA = {
    'steps': InputSpec(node=ref('ksampler'), field='steps', default=None, infer_type=False),
    'model': InputSpec(node=ref('unetloader'), field='unet_name', default=None, infer_type=False),
    'seed': InputSpec(node=ref('ksampler'), field='seed', default=DEFAULT_SEED, type='INT'),
}

CANONICAL_CUSTODY = {'dualcliploader': {'id': '105',
                    'uid': '105',
                    'class_type': 'DualCLIPLoader',
                    'native_ports': {'native_input_names': ['clip_name1', 'clip_name2'],
                                     'native_output_names': ['CLIP'],
                                     'native_input_types': ['COMBO', 'COMBO'],
                                     'native_output_types': ['CLIP'],
                                     'native_input_optional': [False, False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['CLIP'],
                                 'output_types': ['CLIP'],
                                 'keep_defaults': ['clip_name1', 'clip_name2', 'device', 'type']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'vaeloader': {'id': '106',
               'uid': '106',
               'class_type': 'VAELoader',
               'native_ports': {'native_input_names': ['vae_name'],
                                'native_output_names': ['VAE'],
                                'native_input_types': ['COMBO'],
                                'native_output_types': ['VAE'],
                                'native_input_optional': [False],
                                'native_input_asset_kinds': None,
                                'native_output_slots': None},
               'metadata': {'schema_source': {'provider': 'object_info_index',
                                              'path': None,
                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                              'server_url': None,
                                              'package': 'comfy_core',
                                              'version': None,
                                              'hash': None,
                                              'confidence': 0.7},
                            'provenance': 'untrusted_source',
                            'output_names': ['VAE'],
                            'output_types': ['VAE'],
                            'keep_defaults': ['vae_name']},
               'widget_channels': {},
               'none_input_fields': [],
               'none_widget_fields': [],
               'output_slot_names': {}},
 'emptyacestep1_5latentaudio': {'id': '122',
                                'uid': '122',
                                'class_type': 'EmptyAceStep1.5LatentAudio',
                                'native_ports': {'native_input_names': ['seconds'],
                                                 'native_output_names': ['LATENT'],
                                                 'native_input_types': ['FLOAT'],
                                                 'native_output_types': ['LATENT'],
                                                 'native_input_optional': [False],
                                                 'native_input_asset_kinds': None,
                                                 'native_output_slots': None},
                                'metadata': {'schema_source': {'provider': 'object_info_index',
                                                               'path': None,
                                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                               'server_url': None,
                                                               'package': 'comfy_core',
                                                               'version': None,
                                                               'hash': None,
                                                               'confidence': 0.7},
                                             'provenance': 'untrusted_source',
                                             'output_names': ['LATENT'],
                                             'output_types': ['LATENT'],
                                             'keep_defaults': ['batch_size']},
                                'widget_channels': {},
                                'none_input_fields': [],
                                'none_widget_fields': [],
                                'output_slot_names': {}},
 'unetloader': {'id': '125',
                'uid': '125',
                'class_type': 'UNETLoader',
                'native_ports': {'native_input_names': ['unet_name'],
                                 'native_output_names': ['MODEL'],
                                 'native_input_types': ['COMBO'],
                                 'native_output_types': ['MODEL'],
                                 'native_input_optional': [False],
                                 'native_input_asset_kinds': None,
                                 'native_output_slots': None},
                'metadata': {'schema_source': {'provider': 'object_info_index',
                                               'path': None,
                                               'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                               'server_url': None,
                                               'package': 'comfy_core',
                                               'version': None,
                                               'hash': None,
                                               'confidence': 0.7},
                             'provenance': 'untrusted_source',
                             'output_names': ['MODEL'],
                             'output_types': ['MODEL'],
                             'keep_defaults': ['unet_name', 'weight_dtype']},
                'widget_channels': {},
                'none_input_fields': [],
                'none_widget_fields': [],
                'output_slot_names': {}},
 'modelsamplingauraflow': {'id': '78',
                           'uid': '78',
                           'class_type': 'ModelSamplingAuraFlow',
                           'native_ports': {'native_input_names': ['model'],
                                            'native_output_names': ['MODEL'],
                                            'native_input_types': ['MODEL'],
                                            'native_output_types': ['MODEL'],
                                            'native_input_optional': [False],
                                            'native_input_asset_kinds': None,
                                            'native_output_slots': None},
                           'metadata': {'schema_source': {'provider': 'object_info_index',
                                                          'path': None,
                                                          'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                          'server_url': None,
                                                          'package': 'comfy_core',
                                                          'version': None,
                                                          'hash': None,
                                                          'confidence': 0.7},
                                        'provenance': 'untrusted_source',
                                        'output_names': ['MODEL'],
                                        'output_types': ['MODEL'],
                                        'keep_defaults': ['shift']},
                           'widget_channels': {},
                           'none_input_fields': [],
                           'none_widget_fields': [],
                           'output_slot_names': {}},
 'textencodeacestepaudio1_5': {'id': '124',
                               'uid': '124',
                               'class_type': 'TextEncodeAceStepAudio1.5',
                               'native_ports': {'native_input_names': ['clip',
                                                                       'tags',
                                                                       'lyrics',
                                                                       'seed',
                                                                       'duration',
                                                                       'timesignature',
                                                                       'language',
                                                                       'keyscale',
                                                                       'generate_audio_codes',
                                                                       'cfg_scale'],
                                                'native_output_names': ['CONDITIONING'],
                                                'native_input_types': ['CLIP',
                                                                       'STRING',
                                                                       'STRING',
                                                                       'INT',
                                                                       'FLOAT',
                                                                       'COMBO',
                                                                       'COMBO',
                                                                       'COMBO',
                                                                       'BOOLEAN',
                                                                       'FLOAT'],
                                                'native_output_types': ['CONDITIONING'],
                                                'native_input_optional': [False,
                                                                          False,
                                                                          False,
                                                                          False,
                                                                          False,
                                                                          False,
                                                                          False,
                                                                          False,
                                                                          False,
                                                                          False],
                                                'native_input_asset_kinds': None,
                                                'native_output_slots': None},
                               'metadata': {'schema_source': {'provider': 'object_info_index',
                                                              'path': None,
                                                              'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                              'server_url': None,
                                                              'package': 'comfy_core',
                                                              'version': None,
                                                              'hash': None,
                                                              'confidence': 0.7},
                                            'provenance': 'untrusted_source',
                                            'output_names': ['CONDITIONING'],
                                            'output_types': ['CONDITIONING'],
                                            'keep_defaults': ['bpm',
                                                              'cfg_scale',
                                                              'control_after_generate',
                                                              'generate_audio_codes',
                                                              'keyscale',
                                                              'language',
                                                              'lyrics',
                                                              'min_p',
                                                              'tags',
                                                              'temperature',
                                                              'timesignature',
                                                              'top_k',
                                                              'top_p']},
                               'widget_channels': {},
                               'none_input_fields': [],
                               'none_widget_fields': [],
                               'output_slot_names': {}},
 'conditioningzeroout': {'id': '47',
                         'uid': '47',
                         'class_type': 'ConditioningZeroOut',
                         'native_ports': {'native_input_names': ['conditioning'],
                                          'native_output_names': ['CONDITIONING'],
                                          'native_input_types': ['CONDITIONING'],
                                          'native_output_types': ['CONDITIONING'],
                                          'native_input_optional': [False],
                                          'native_input_asset_kinds': None,
                                          'native_output_slots': None},
                         'metadata': {'schema_source': {'provider': 'object_info_index',
                                                        'path': None,
                                                        'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                        'server_url': None,
                                                        'package': 'comfy_core',
                                                        'version': None,
                                                        'hash': None,
                                                        'confidence': 0.7},
                                      'provenance': 'untrusted_source',
                                      'output_names': ['CONDITIONING'],
                                      'output_types': ['CONDITIONING']},
                         'widget_channels': {},
                         'none_input_fields': [],
                         'none_widget_fields': [],
                         'output_slot_names': {}},
 'ksampler': {'id': '3',
              'uid': '3',
              'class_type': 'KSampler',
              'native_ports': {'native_input_names': ['model',
                                                      'positive',
                                                      'negative',
                                                      'latent_image',
                                                      'seed'],
                               'native_output_names': ['LATENT'],
                               'native_input_types': ['MODEL',
                                                      'CONDITIONING',
                                                      'CONDITIONING',
                                                      'LATENT',
                                                      'INT'],
                               'native_output_types': ['LATENT'],
                               'native_input_optional': [False, False, False, False, False],
                               'native_input_asset_kinds': None,
                               'native_output_slots': None},
              'metadata': {'schema_source': {'provider': 'object_info_index',
                                             'path': None,
                                             'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                             'server_url': None,
                                             'package': 'comfy_core',
                                             'version': None,
                                             'hash': None,
                                             'confidence': 0.7},
                           'provenance': 'untrusted_source',
                           'output_names': ['LATENT'],
                           'output_types': ['LATENT'],
                           'keep_defaults': ['cfg',
                                             'control_after_generate',
                                             'denoise',
                                             'sampler_name',
                                             'scheduler',
                                             'steps']},
              'widget_channels': {},
              'none_input_fields': [],
              'none_widget_fields': [],
              'output_slot_names': {}},
 'vaedecodeaudio': {'id': '123',
                    'uid': '123',
                    'class_type': 'VAEDecodeAudio',
                    'native_ports': {'native_input_names': ['samples', 'vae'],
                                     'native_output_names': ['AUDIO'],
                                     'native_input_types': ['LATENT', 'VAE'],
                                     'native_output_types': ['AUDIO'],
                                     'native_input_optional': [False, False],
                                     'native_input_asset_kinds': None,
                                     'native_output_slots': None},
                    'metadata': {'schema_source': {'provider': 'object_info_index',
                                                   'path': None,
                                                   'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                   'server_url': None,
                                                   'package': 'comfy_core',
                                                   'version': None,
                                                   'hash': None,
                                                   'confidence': 0.7},
                                 'provenance': 'untrusted_source',
                                 'output_names': ['AUDIO'],
                                 'output_types': ['AUDIO']},
                    'widget_channels': {},
                    'none_input_fields': [],
                    'none_widget_fields': [],
                    'output_slot_names': {}},
 'saveaudiomp3': {'id': '59',
                  'uid': '59',
                  'class_type': 'SaveAudioMP3',
                  'native_ports': {'native_input_names': ['audio'],
                                   'native_output_names': [],
                                   'native_input_types': ['AUDIO'],
                                   'native_output_types': [],
                                   'native_input_optional': [False],
                                   'native_input_asset_kinds': None,
                                   'native_output_slots': None},
                  'metadata': {'schema_source': {'provider': 'object_info_index',
                                                 'path': None,
                                                 'cache_path': '/Users/hannahomalley/Documents/Codex/2026-09-08/goal-continue-the-existing-megado-plan/VibeComfy-integrity/.otto/worktrees/unified-workflow-integrity-20260909/vibecomfy/porting/cache/object_info/comfy_core@object_info_comfyui_0.24.0.1.json',
                                                 'server_url': None,
                                                 'package': 'comfy_core',
                                                 'version': None,
                                                 'hash': None,
                                                 'confidence': 0.7},
                               'provenance': 'untrusted_source',
                               'keep_defaults': ['filename_prefix', 'quality']},
                  'widget_channels': {},
                  'none_input_fields': [],
                  'none_widget_fields': [],
                  'output_slot_names': {}}}
HELPER_CUSTODY = [{'id': '110',
  'uid': '110',
  'class_type': 'PrimitiveFloat',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': ['value'],
                   'native_output_names': ['FLOAT'],
                   'native_input_types': ['FLOAT'],
                   'native_output_types': ['FLOAT'],
                   'native_input_optional': [False],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}},
 {'id': '126',
  'uid': '126',
  'class_type': 'PrimitiveNode',
  'provenance': 'untrusted_source',
  'native_ports': {'native_input_names': [],
                   'native_output_names': ['INT'],
                   'native_input_types': [],
                   'native_output_types': ['INT'],
                   'native_input_optional': [],
                   'native_input_asset_kinds': None,
                   'native_output_slots': None}}]

READY_METADATA = ReadyMetadata.build(
    capability='audio',
    template_id='ace_step_1_5_t2a_song',
    inputs=PUBLIC_INPUT_METADATA,
    requirements={'models': ['ace_1.5_vae.safetensors', 'acestep_v1.5_turbo.safetensors'], 'custom_nodes': ['EmptyAceStep1', 'TextEncodeAceStepAudio1']},
    provenance={'source_path': 'ready_templates/sources/official/audio/ace_step_1_5_t2a_song.json', 'source_id': 'ace_step_1_5_t2a_song', 'source_type': 'api', 'source_workflow_path': 'ready_templates/sources/official/audio/ace_step_1_5_t2a_song.json', 'source_ref': 'ready_templates/sources/official/audio/ace_step_1_5_t2a_song.json', 'source_kind': 'raw_json', 'indexed_id': None, 'workflow_source_id': 'ace_step_1_5_t2a_song', 'workflow_source_type': 'api', 'raw_workflow_shape': 'ui', 'source_hash': 'sha256:820e0899c2996967929a8e1632c35da6c4fa52d0e5b503ec374ca44f58ba4494', 'workflow_shape': {'nodes': 12, 'runtime_nodes': 12, 'helper_nodes': 0, 'edges': 14, 'inputs': 2, 'outputs': 1}, 'output_mode': 'scratchpad'},
)

def build() -> VibeWorkflow:
    """Build the workflow (auto-generated)."""
    wf = new_workflow(READY_METADATA, source_path=__file__, canonical_custody=CANONICAL_CUSTODY)

    # Loaders
    dualcliploader = DualCLIPLoader(
        clip_name1=CLIP_NAME,
        clip_name2=CLIP_NAME_2,
        type='ace',
        device='default',
    )

    vaeloader = VAELoader(vae_name=VAE_NAME)
    emptyacestep1_5latentaudio = EmptyAceStep1_5LatentAudio(batch_size=1, seconds=2)
    unetloader = UNETLoader(unet_name=UNET_NAME, weight_dtype='default')

    modelsamplingauraflow = ModelSamplingAuraFlow(
        shift=3,
        model=unetloader.out('MODEL'),
    )

    textencodeacestepaudio1_5 = TextEncodeAceStepAudio1_5(
        tags='synthwave, techno, synthpop, futuristic, electro, with liquid drum & bass drive.\nRestless, confident, dreamy mood at 128 BPM.\nAnalog bass, pulsating arps, percussive synth stabs, gated drums.\nQuick build,  then explosive drum burst, then clean fade.\nBreathy, rhythmic female vocals, minimal emotion, metallic echo.',
        lyrics='Verse\nNeon rain on my screen,\nDreams compile in silver sheen.\nNo weight, just motion,\nI’m plugged into emotion.\n\nChorus\nComfy Cloud — breathing light,\nCode and color, spark and wire.\nDrift through data, feel alive,\nIn your circuits, I arrive.',
        seed=DEFAULT_SEED,
        duration=2,
        bpm=120,
        timesignature='4',
        language='en',
        keyscale='E minor',
        generate_audio_codes=True,
        cfg_scale=1.5,
        temperature=0.85,
        top_p=0.9,
        top_k=0,
        min_p=0,
        control_after_generate=FIXED,
        clip=dualcliploader.out('CLIP'),
    )

    conditioningzeroout = ConditioningZeroOut(
        conditioning=textencodeacestepaudio1_5.out('CONDITIONING'),
    )

    # Sampling
    ksampler = KSampler(
        seed=DEFAULT_SEED,
        steps=1,
        cfg=GUIDE_STRENGTH,
        sampler_name='euler',
        scheduler='simple',
        denoise=1,
        control_after_generate=FIXED,
        latent_image=emptyacestep1_5latentaudio.out('LATENT'),
        model=modelsamplingauraflow.out('MODEL'),
        negative=conditioningzeroout.out('CONDITIONING'),
        positive=textencodeacestepaudio1_5.out('CONDITIONING'),
    )

    vaedecodeaudio = VAEDecodeAudio(
        samples=ksampler.out('LATENT'),
        vae=vaeloader.out('VAE'),
    )

    # Outputs
    saveaudiomp3 = SaveAudioMP3(
        filename_prefix='audio/vibecomfy_ace_step_smoke',
        quality='V0',
        audio=vaedecodeaudio.out('AUDIO'),
    )

    wf = wf.finalize(PUBLIC_INPUT_METADATA, canonical_outputs=[{'node': saveaudiomp3, 'output_type': 'SaveAudioMP3', 'name': None, 'artifact_kind': None, 'mime_type': None, 'filename_prefix': None, 'expected_cardinality': None}], canonical_requirements={'models': ['ace_1.5_vae.safetensors', 'acestep_v1.5_turbo.safetensors'], 'custom_nodes': ['EmptyAceStep1', 'TextEncodeAceStepAudio1'], 'missing_models': [], 'missing_nodes': [], 'unsupported': []}, canonical_custody=CANONICAL_CUSTODY, canonical_bindings={'dualcliploader': dualcliploader, 'vaeloader': vaeloader, 'emptyacestep1_5latentaudio': emptyacestep1_5latentaudio, 'unetloader': unetloader, 'modelsamplingauraflow': modelsamplingauraflow, 'textencodeacestepaudio1_5': textencodeacestepaudio1_5, 'conditioningzeroout': conditioningzeroout, 'ksampler': ksampler, 'vaedecodeaudio': vaedecodeaudio, 'saveaudiomp3': saveaudiomp3}, canonical_helpers=HELPER_CUSTODY)
    wf.strict_types = False
    return wf
